// GENERATED by sfm-propagate-changes; edit the primary source or reconcile this file.
package ca.teamdman.sfml.ast;

public interface ToStringPretty {
    default String toStringPretty() {
        return this.toString();
    }
}
