//! Post-promotion source-and-registration contracts for six mixin inputs.
//!
//! Real authored-core selection and text collection run in isolated source-only
//! fixtures. Historical objects are bounded witnesses, never production inputs.
//! Synthetic Gradle files attest neither locks nor Java/native/gameplay builds.
//! Independently enabled ingress subsets are reviewed reconstructions, not raw
//! historical-output claims.

#![cfg(test)]

use super::candidate_lock::checked_file;
use super::context::ProjectionContext;
use super::core_inputs::CORE_ROOT;
use super::core_inputs::CoreProjectInputs;
use super::core_inputs::InputPredicate;
use super::core_inputs::InputVariant;
use super::core_inputs::collect_core_artifacts;
use super::core_inputs::discover_core_source_files;
use super::core_inputs::select_core_inputs;
use super::core_slice_test_support::CoreTestFixture;
use super::core_slice_test_support::read_bounded;
use super::core_slice_test_support::read_git_blobs;
use super::provenance::sha256;
use super::render_java_source;
use eyre::Result;
use eyre::ensure;
use facet::Facet;
use std::collections::BTreeMap;
use std::collections::BTreeSet;
use std::fs;
use std::path::Path;
use std::path::PathBuf;

const LEDGER: &str = "docs/tasks/sfm-core-mixin-closure-slice.json";
// Independent synthetic collector-fixture inputs, not a native build recipe.
const REQUIRED_PROJECT_FILES: &[&str] = &[
    "build.gradle",
    "settings.gradle",
    "gradle.properties",
    "gradlew",
    "gradlew.bat",
    "sfm-toolchain.lock.json",
    "gradle/wrapper/gradle-wrapper.properties",
    "gradle/wrapper/gradle-wrapper.jar",
];
const STAGE_PREFIX: &str = "platform/cli/sfm-propagate-changes/target/core-mixin-closure-stage-v1/";
const MIXIN_PREFIX: &str = "src/main/java/ca/teamdman/sfm/mixins/";
const RESOURCE: &str = "src/main/resources/sfm.mixins.json";
const JAVA_BANNER: &[u8] =
    b"// GENERATED by sfm-propagate-changes; edit the primary source or reconcile this file.\n";
const SINGLE: &str = "single_line_input";
const TYPED: &str = "typed_command_palette";
const PUPPET: &str = "game_puppet_runtime";
const KEYS: &str = "keyboard_profiles";
const OVERLAY: &str = "client_overlay_input";
const POINTER: &str = "pointer_modifier_ingress";
const OWNERS: [&str; 6] = [SINGLE, TYPED, PUPPET, KEYS, OVERLAY, POINTER];
const TARGETS: [&str; 10] = [
    "1.19.2", "1.19.4", "1.20", "1.20.1", "1.20.2", "1.20.3", "1.20.4", "1.21.0", "1.21.1",
    "26.1.2",
];
const COMMITS: [(&str, &str); 20] = [
    ("dev/1.19.2", "f3ff2f6425434f36c7c680fa909c977b158e1860"),
    ("dev/1.19.4", "2e3b561c15d663fb89fd353ccc2af67eeb0c2053"),
    ("dev/1.20", "6bf4845761d06560fc5e0e36018b5d583589004d"),
    ("dev/1.20.1", "faa040ce14dd825f2dd9716ea59508bf46278c06"),
    ("dev/1.20.2", "a829fb4db2ae06eddd2defb22e33f0b45a4b3ff9"),
    ("dev/1.20.3", "704aa69edad5376d8d6cfb0b0ef7845af077e647"),
    ("dev/1.20.4", "11d3ed07d654ff801329f17cf1eb81c2b347eecd"),
    ("dev/1.21.0", "43068d610b1c053c6569be486439769eec2ae9ef"),
    ("dev/1.21.1", "7524ab5512878b773e212600c9578b2bc4db4717"),
    ("dev/26.1.2", "6bd27f03863ddd041344cbc3da51b01a7b3c3e1f"),
    ("release/1.19.2", "31135b8e86801b862d5cb2283c7c5878b7cc5bb4"),
    ("release/1.19.4", "23785b63e3e1fe35e5be6a6d89b6638ee0ff0daa"),
    ("release/1.20", "3df18123a19535fd0e5d1dc81aa302105c3fd2f6"),
    ("release/1.20.1", "bb5babf12f467235b3a44ad5098666ee3ed171ec"),
    ("release/1.20.2", "cfbbafaeda4a006ae32743a92de330711983056b"),
    ("release/1.20.3", "1b7f9605da0ef13c7601daf3786545868dfc3c78"),
    ("release/1.20.4", "a637581b5e1078d7cc0ca68333add568e3e387ff"),
    ("release/1.21.0", "6bfab8a21e7a5bbeb0bb136bf4e5b26f6ce03e25"),
    ("release/1.21.1", "f5366c79c823ff52712130e69dd9c8166c70bd14"),
    ("release/26.1.2", "fe32b29453b13b4f3050ad441677c7eb79e80814"),
];
#[derive(Clone, Copy)]
struct Golden {
    oid: &'static str,
    raw_sha256: &'static str,
    raw_bytes: usize,
    crlf: usize,
    raw_final_lf: bool,
    append_lf: bool,
    normalized_sha256: &'static str,
    normalized_bytes: usize,
}
const GOLDENS: [Golden; 12] = [
    Golden {
        oid: "17e22857c0761e2c87922ead1ae53460c126ebee",
        raw_sha256: "sha256:450fea7782b05412c45273ce78dadfd51718dc28cbac7ff7c94d88deb61ecff8",
        raw_bytes: 786,
        crlf: 0,
        raw_final_lf: true,
        append_lf: false,
        normalized_sha256: "sha256:450fea7782b05412c45273ce78dadfd51718dc28cbac7ff7c94d88deb61ecff8",
        normalized_bytes: 786,
    },
    Golden {
        oid: "345209e2410d3b382ca46b284631d552aa8256cd",
        raw_sha256: "sha256:dfc7dd8c0adaa183796a87e978af76e20fdc1ce6f1556065ead26f45dc80a2c0",
        raw_bytes: 2131,
        crlf: 0,
        raw_final_lf: true,
        append_lf: false,
        normalized_sha256: "sha256:dfc7dd8c0adaa183796a87e978af76e20fdc1ce6f1556065ead26f45dc80a2c0",
        normalized_bytes: 2131,
    },
    Golden {
        oid: "643ea852e5cab170c4e8c39fe5af2e3e1cb289b0",
        raw_sha256: "sha256:3779bf0a7c4b432c38fb78671a0b3ebb8a547207249acd3e0363f71485c36937",
        raw_bytes: 2743,
        crlf: 0,
        raw_final_lf: true,
        append_lf: false,
        normalized_sha256: "sha256:3779bf0a7c4b432c38fb78671a0b3ebb8a547207249acd3e0363f71485c36937",
        normalized_bytes: 2743,
    },
    Golden {
        oid: "8d0b4466929dc3fb03006cdbc1996a10b4590eb7",
        raw_sha256: "sha256:5a40a2cb8f8ca86a301a0d01a1cfb7acbfdff8b4f23e01aa50ee00305b93d3e0",
        raw_bytes: 376,
        crlf: 0,
        raw_final_lf: true,
        append_lf: false,
        normalized_sha256: "sha256:5a40a2cb8f8ca86a301a0d01a1cfb7acbfdff8b4f23e01aa50ee00305b93d3e0",
        normalized_bytes: 376,
    },
    Golden {
        oid: "b1ebd296ef3f8dcf4d084b8570acce3b021a2a8e",
        raw_sha256: "sha256:0a6822f502c033b374484165b6fa167d9514f0397e46e04ef799d550669ba24c",
        raw_bytes: 869,
        crlf: 0,
        raw_final_lf: true,
        append_lf: false,
        normalized_sha256: "sha256:0a6822f502c033b374484165b6fa167d9514f0397e46e04ef799d550669ba24c",
        normalized_bytes: 869,
    },
    Golden {
        oid: "ba825c149ae9d855d4d2ee43698940fefc99dfe8",
        raw_sha256: "sha256:05ef4881dfd569c0fe8a86f75ee8560a6bb9d64e3c76bdc971ff1ec0e6453056",
        raw_bytes: 884,
        crlf: 0,
        raw_final_lf: true,
        append_lf: false,
        normalized_sha256: "sha256:05ef4881dfd569c0fe8a86f75ee8560a6bb9d64e3c76bdc971ff1ec0e6453056",
        normalized_bytes: 884,
    },
    Golden {
        oid: "e13e89eb58fdbfe161439410b81d6c3e8e3971ed",
        raw_sha256: "sha256:a8f0bed0419f7578832d2d15970a9b6587e6049780c30158ebe67fce8ec53f56",
        raw_bytes: 609,
        crlf: 0,
        raw_final_lf: true,
        append_lf: false,
        normalized_sha256: "sha256:a8f0bed0419f7578832d2d15970a9b6587e6049780c30158ebe67fce8ec53f56",
        normalized_bytes: 609,
    },
    Golden {
        oid: "490bd91c6590f0595bc1696f973878facd565539",
        raw_sha256: "sha256:a0775e35b9f7c658d8576769c001e7bc08cc04c38240d275e1b4fb607d7cb29f",
        raw_bytes: 435,
        crlf: 13,
        raw_final_lf: true,
        append_lf: false,
        normalized_sha256: "sha256:cf8282a22369432a35858c6a5bf18138add567a1cc0d49f172c8904b26277f0e",
        normalized_bytes: 422,
    },
    Golden {
        oid: "a0801d4819eb013530d61d3dfd15c6a8195b8cc4",
        raw_sha256: "sha256:030e074ee486e20289ebfa74d7f0253cf5e946a04bd4e4680f77e7bec91711b7",
        raw_bytes: 332,
        crlf: 17,
        raw_final_lf: true,
        append_lf: false,
        normalized_sha256: "sha256:dfec94ab4f7b6ca1be17cb4a46ec88dc2a7097b97a68f1027b6dd48b5d35e0d1",
        normalized_bytes: 315,
    },
    Golden {
        oid: "db375db533741395a944058540944607e8421332",
        raw_sha256: "sha256:931691b1a3864896a6643e2d97049ab02754f4fac2c4f6cae30d6bf130a83db9",
        raw_bytes: 374,
        crlf: 18,
        raw_final_lf: true,
        append_lf: false,
        normalized_sha256: "sha256:4f9092a4a7d5f868c827577e9b9801fc6442c6572874e85c74b3fbb0e2cd70d1",
        normalized_bytes: 356,
    },
    Golden {
        oid: "a4e7d758c662139d819e6ab031b1553dcb402684",
        raw_sha256: "sha256:6bac015c9c8be2258a8613a0fb4ea0e6de94bc5ddf21e9cec0d6b1f02174ca3a",
        raw_bytes: 304,
        crlf: 15,
        raw_final_lf: false,
        append_lf: true,
        normalized_sha256: "sha256:035386d2378de6806fbd703063a65929d25a08e0e2143deac1e9246cb6c2efa3",
        normalized_bytes: 290,
    },
    Golden {
        oid: "e5a17eabd50c4c5fd49e07e2a9e189fdad872034",
        raw_sha256: "sha256:3af85f62841d9a65770c869cd5990e9716da942f520ede806a3383b66d7e52c8",
        raw_bytes: 346,
        crlf: 16,
        raw_final_lf: false,
        append_lf: true,
        normalized_sha256: "sha256:2e5d71d2aac2738d1cf33add5321334ed91fe9f3f870d1887718a474ef40c50e",
        normalized_bytes: 331,
    },
];
#[derive(Clone, Copy)]
struct Source {
    path: &'static str,
    template_sha256: &'static str,
    template_bytes: usize,
}
const SOURCES: [Source; 6] = [
    Source {
        path: "src/main/java/ca/teamdman/sfm/mixins/EditBoxAccessor.java",
        template_sha256: "sha256:5a40a2cb8f8ca86a301a0d01a1cfb7acbfdff8b4f23e01aa50ee00305b93d3e0",
        template_bytes: 376,
    },
    Source {
        path: "src/main/java/ca/teamdman/sfm/mixins/MouseHandlerMixin.java",
        template_sha256: "sha256:69d5b6a7d3ae036a8f136c2ce99b58fd7adc56c4bfe72c851102580443188ed8",
        template_bytes: 3808,
    },
    Source {
        path: "src/main/java/ca/teamdman/sfm/mixins/MouseHandlerInvoker.java",
        template_sha256: "sha256:450fea7782b05412c45273ce78dadfd51718dc28cbac7ff7c94d88deb61ecff8",
        template_bytes: 786,
    },
    Source {
        path: "src/main/java/ca/teamdman/sfm/mixins/KeyboardHandlerMixin.java",
        template_sha256: "sha256:1625771bdf9353245a099751e968eb3403b4e4365b256daee6cf1e0568780b22",
        template_bytes: 2476,
    },
    Source {
        path: "src/main/java/ca/teamdman/sfm/mixins/KeyboardHandlerInvoker.java",
        template_sha256: "sha256:a8f0bed0419f7578832d2d15970a9b6587e6049780c30158ebe67fce8ec53f56",
        template_bytes: 609,
    },
    Source {
        path: "src/main/resources/sfm.mixins.json",
        template_sha256: "sha256:ae39118f9b82fa23034556d1764347577858c15fcc8badb18696d64744597c86",
        template_bytes: 1596,
    },
];
#[derive(Facet)]
struct Ledger {
    schema: String,
    scope: String,
    stage_prefix: String,
    context_commits: BTreeMap<String, String>,
    files: Vec<FileEvidence>,
}
#[derive(Facet)]
struct FileEvidence {
    path: String,
    intended_core_path: String,
    stage_path: String,
    template_sha256: String,
    template_bytes: usize,
    source_rules_suggestion: Vec<InputVariant>,
    raw_variants: Vec<RawEvidence>,
    witnesses: Vec<Witness>,
}
#[derive(Facet)]
struct RawEvidence {
    oid: String,
    raw_bytes: usize,
    raw_sha256: String,
    crlf_count: usize,
    lone_cr_count: usize,
    raw_final_lf: bool,
    append_lf: bool,
    normalized_bytes: usize,
    normalized_sha256: String,
    normalization: String,
}
#[derive(Facet)]
struct Witness {
    context: String,
    source_commit: String,
    present: bool,
    oid: Option<String>,
    git_mode: Option<String>,
    explicit_owner_roots: Vec<String>,
    feature_context_origin: String,
    proof: String,
    authoring_reconstruction_equal: Option<bool>,
}
#[derive(Facet)]
#[facet(deny_unknown_fields)]
struct Registration {
    required: bool,
    #[facet(rename = "minVersion")]
    min_version: String,
    package: String,
    refmap: String,
    #[facet(rename = "compatibilityLevel")]
    compatibility_level: String,
    mixins: Vec<String>,
    client: Vec<String>,
    server: Vec<String>,
    injectors: Injectors,
}
#[derive(Facet)]
#[facet(deny_unknown_fields)]
struct Injectors {
    #[facet(rename = "defaultRequire")]
    default_require: usize,
}
struct Fixture {
    core: CoreTestFixture,
    inventory: BTreeSet<String>,
    raw: BTreeMap<String, Vec<u8>>,
    normalized: BTreeMap<String, Vec<u8>>,
}
impl Fixture {
    fn load() -> Result<Self> {
        let core = CoreTestFixture::load()?;
        let bytes = read_bounded(&checked_file(&core.repository, LEDGER)?, 1024 * 1024)?;
        let ledger: Ledger = facet_json::from_str(std::str::from_utf8(&bytes)?)?;
        let commits: BTreeMap<String, String> = COMMITS
            .into_iter()
            .map(|(c, id)| (c.to_owned(), id.to_owned()))
            .collect();
        ensure!(
            ledger.schema == "sfm:core_mixin_closure_slice@1"
                && ledger.scope
                    == "six_authored_source_and_registration_inputs_staged_only_not_live_core"
                && ledger.stage_prefix == STAGE_PREFIX
                && ledger.context_commits == commits
                && ledger.files.len() == 6,
            "mixin ledger identity or fixed scope drift"
        );
        let mut seen_paths = BTreeSet::new();
        let mut seen_blobs = BTreeSet::new();
        let mut cells = (0, 0);
        for file in ledger.files {
            let selected_source = source(&file.path)?;
            ensure!(
                seen_paths.insert(file.path.clone())
                    && file.intended_core_path == format!("{CORE_ROOT}/{}", selected_source.path)
                    && file.stage_path == format!("{STAGE_PREFIX}{}", selected_source.path)
                    && file.template_sha256 == selected_source.template_sha256
                    && file.template_bytes == selected_source.template_bytes
                    && file.source_rules_suggestion == vec![expected_rule(selected_source)],
                "mixin authored owner, mode, path or hash drift"
            );
            verify_metadata(&core.metadata, selected_source)?;
            let mut file_oids = BTreeSet::new();
            for evidence in file.raw_variants {
                let fixed = golden(&evidence.oid)?;
                ensure!(
                    file_oids.insert(evidence.oid.clone())
                        && seen_blobs.insert(evidence.oid)
                        && evidence.raw_bytes == fixed.raw_bytes
                        && evidence.raw_sha256 == fixed.raw_sha256
                        && evidence.crlf_count == fixed.crlf
                        && evidence.lone_cr_count == 0
                        && evidence.raw_final_lf == fixed.raw_final_lf
                        && evidence.append_lf == fixed.append_lf
                        && evidence.normalized_bytes == fixed.normalized_bytes
                        && evidence.normalized_sha256 == fixed.normalized_sha256
                        && evidence.normalization == normalization_name(fixed),
                    "mixin raw witness or approved whitespace boundary drift"
                );
            }
            let expected_count = if selected_source.path == RESOURCE {
                5
            } else if selected_source.path.ends_with("MouseHandlerMixin.java") {
                3
            } else {
                1
            };
            ensure!(
                file_oids.len() == expected_count && file.witnesses.len() == 20,
                "mixin variant count drift"
            );
            let mut contexts = BTreeSet::new();
            for witness in file.witnesses {
                let (environment, target) = witness
                    .context
                    .split_once('/')
                    .ok_or_else(|| eyre::eyre!("malformed frozen mixin context"))?;
                let expected = expected_oid(selected_source.path, environment == "dev", target)?;
                let roots = witness_roots(environment, target);
                ensure!(
                    contexts.insert(witness.context.clone())
                        && commits.get(&witness.context) == Some(&witness.source_commit)
                        && witness.present == expected.is_some()
                        && witness.oid.as_deref() == expected
                        && same_names(&witness.explicit_owner_roots, &roots)
                        && witness.feature_context_origin
                            == "reconstructed_explicit_owner_selection_not_historical_feature_flag_claim",
                    "mixin fixed context or owner roots drift"
                );
                if let Some(oid) = expected {
                    ensure!(
                        file_oids.contains(oid)
                            && witness.git_mode.as_deref() == Some("100644")
                            && witness.proof
                                == "independent_literal_authoring_reconstruction_not_production_renderer"
                            && witness.authoring_reconstruction_equal == Some(true),
                        "mixin present witness drift"
                    );
                    cells.0 += 1;
                } else {
                    ensure!(
                        witness.git_mode.is_none()
                            && witness.proof
                                == "frozen_tree_membership_absence_not_renderer_omission_proof"
                            && witness.authoring_reconstruction_equal.is_none(),
                        "mixin absence gained historical bytes"
                    );
                    cells.1 += 1;
                }
                closed_context(&core, target, &roots)?;
            }
            ensure!(
                contexts == commits.keys().cloned().collect(),
                "mixin incomplete context scope"
            );
        }
        ensure!(
            seen_paths.len() == 6 && seen_blobs.len() == 12 && cells == (38, 82),
            "mixin fixed matrix drift"
        );
        let raw = read_git_blobs(&core.repository, &seen_blobs)?;
        let mut normalized = BTreeMap::new();
        for fixed in GOLDENS {
            normalized.insert(fixed.oid.to_owned(), normalize_raw(&raw[fixed.oid], fixed)?);
        }
        let inventory = discover_core_source_files(&core.core)?;
        for selected_source in SOURCES {
            ensure!(
                inventory.contains(selected_source.path),
                "mixin source not promoted"
            );
            verify_current_template(
                &read_bounded(
                    &checked_file(&core.core, selected_source.path)?,
                    1024 * 1024,
                )?,
                selected_source,
            )?;
        }
        Ok(Self {
            core,
            inventory,
            raw,
            normalized,
        })
    }
    fn isolated(&self) -> Result<Isolated> {
        let temp = tempfile::tempdir()?;
        let root = temp.path().join(CORE_ROOT);
        fs::create_dir_all(&root)?;
        let mut metadata = self.core.metadata.clone();
        metadata
            .source_rules
            .retain(|path, _| SOURCES.iter().any(|s| s.path == path));
        metadata.project_files.clear();
        for selected_source in SOURCES {
            let bytes = read_bounded(
                &checked_file(&self.core.core, selected_source.path)?,
                1024 * 1024,
            )?;
            write_fixture(&root, selected_source.path, &bytes)?;
        }
        for output in REQUIRED_PROJECT_FILES {
            metadata.project_files.insert(
                (*output).to_owned(),
                vec![InputVariant {
                    input: format!("build/isolated-mixin-source-fixture/{output}"),
                    when: InputPredicate::default(),
                    template: false,
                }],
            );
        }
        Ok(Isolated {
            _temp: temp,
            root,
            metadata,
        })
    }
    fn verify_class_closure(
        &self,
        context: &ProjectionContext,
        outputs: &BTreeMap<String, Vec<u8>>,
    ) -> Result<()> {
        let selection = self
            .core
            .selection_for_assertion(context, &self.inventory)?;
        let registration: Registration =
            facet_json::from_str(std::str::from_utf8(&outputs[RESOURCE])?)?;
        ensure!(
            !registration.required
                && registration.min_version == "0.8.3"
                && registration.package == "ca.teamdman.sfm.mixins"
                && registration.refmap == "sfm.refmap.json"
                && registration.server.is_empty()
                && registration.injectors.default_require == 1,
            "mixin registration frame changed"
        );
        ensure!(
            registration.compatibility_level
                == if context.minecraft_version == "26.1.2" {
                    "JAVA_25"
                } else {
                    "JAVA_17"
                },
            "mixin Java compatibility changed"
        );
        let expected_common: Vec<String> = if context.minecraft_version == "26.1.2" {
            vec![
                "HopperIgnoreTunnelledManagerMixin".to_owned(),
                "StructureTemplateManagerMixin".to_owned(),
            ]
        } else {
            vec!["StructureTemplateManagerMixin".to_owned()]
        };
        ensure!(
            registration.mixins == expected_common,
            "common mixin registration changed"
        );
        for name in &registration.mixins {
            ensure!(
                selection
                    .inputs
                    .contains_key(&format!("{MIXIN_PREFIX}{name}.java")),
                "registered common mixin class omitted"
            );
        }
        let expected_client = expected_client_names(context);
        ensure!(
            registration.client == expected_client,
            "client registration order or owner predicates drift"
        );
        ensure!(
            registration.client.iter().collect::<BTreeSet<_>>().len() == registration.client.len(),
            "duplicate client mixin registration"
        );
        for selected_source in &SOURCES[..5] {
            let name = class_name(selected_source.path);
            let present = registration
                .client
                .iter()
                .any(|registered| registered == name);
            ensure!(
                selection.inputs.contains_key(selected_source.path) == present
                    && outputs.contains_key(selected_source.path) == present
                    && selection.omitted_paths.contains(selected_source.path) != present,
                "selected class and client registration diverged"
            );
        }
        Ok(())
    }
}
struct Isolated {
    _temp: tempfile::TempDir,
    root: PathBuf,
    metadata: CoreProjectInputs,
}
impl Isolated {
    fn prepare(&self, context: &ProjectionContext) -> Result<BTreeMap<String, Vec<u8>>> {
        let target = target_id(context);
        for output in REQUIRED_PROJECT_FILES {
            let bytes = match *output {
                "gradle.properties" => format!(
                    "minecraft_version={}\nmod_version=source-fixture-only\n",
                    context.minecraft_version
                )
                .into_bytes(),
                "settings.gradle" => format!("rootProject.name = 'sfm-{target}'\n").into_bytes(),
                "gradle/wrapper/gradle-wrapper.properties" => {
                    b"distributionUrl=https\\://example.invalid/gradle-7.5-bin.zip\n".to_vec()
                }
                "gradle/wrapper/gradle-wrapper.jar" => b"\0\xff\x01source-fixture-only".to_vec(),
                _ => b"source-fixture-only\n".to_vec(),
            };
            write_fixture(
                &self.root,
                &format!("build/isolated-mixin-source-fixture/{output}"),
                &bytes,
            )?;
        }
        let inventory = discover_core_source_files(&self.root)?;
        let selection = select_core_inputs(&self.metadata, context, &inventory)?;
        let artifacts = collect_core_artifacts(&self.root, &selection, context)?;
        let mut outputs = BTreeMap::new();
        for selected_source in SOURCES {
            if let Some(artifact) = artifacts.get(selected_source.path) {
                let selected = &selection.inputs[selected_source.path];
                ensure!(
                    selected.input == selected_source.path
                        && selected.template == current_rule(selected_source).template
                        && artifact.source_path == format!("{CORE_ROOT}/{}", selected_source.path)
                        && artifact.overlay.is_none(),
                    "mixin input owner or rendering mode drift: {}",
                    selected_source.path
                );
                let source_text = std::str::from_utf8(&artifact.source_bytes)?;
                let actual = if selected_source.path == RESOURCE {
                    ensure!(
                        !artifact.output_bytes.starts_with(JAVA_BANNER),
                        "Java banner contaminated JSON"
                    );
                    artifact.output_bytes.clone()
                } else {
                    artifact
                        .output_bytes
                        .strip_prefix(JAVA_BANNER)
                        .ok_or_else(|| eyre::eyre!("Java renderer banner missing"))?
                        .to_vec()
                };
                ensure!(
                    actual == render_java_source(source_text, context)?.as_bytes(),
                    "collector bypassed actual controlled renderer"
                );
                outputs.insert(selected_source.path.to_owned(), actual);
            } else {
                ensure!(
                    selection.omitted_paths.contains(selected_source.path),
                    "unowned mixin source absence"
                );
            }
        }
        Ok(outputs)
    }
}
fn target_id(context: &ProjectionContext) -> &str {
    if context.minecraft_version == "1.21" {
        "1.21.0"
    } else {
        &context.minecraft_version
    }
}
fn is_d2(target: &str) -> bool {
    matches!(target, "1.19.2" | "1.19.4")
}
fn source(path: &str) -> Result<Source> {
    SOURCES
        .iter()
        .copied()
        .find(|s| s.path == path)
        .ok_or_else(|| eyre::eyre!("mixin source outside exact cohort"))
}
fn golden(oid: &str) -> Result<Golden> {
    GOLDENS
        .iter()
        .copied()
        .find(|g| g.oid == oid)
        .ok_or_else(|| eyre::eyre!("mixin raw object outside exact frozen set"))
}
fn class_name(path: &str) -> &str {
    path.rsplit('/')
        .next()
        .expect("fixed class path")
        .strip_suffix(".java")
        .expect("fixed Java class")
}
fn same_names(actual: &[String], expected: &[&str]) -> bool {
    actual.len() == expected.len()
        && actual.iter().map(String::as_str).collect::<BTreeSet<_>>()
            == expected.iter().copied().collect()
}
fn witness_roots(environment: &str, target: &str) -> Vec<&'static str> {
    if environment != "dev" {
        vec![]
    } else if is_d2(target) {
        OWNERS.to_vec()
    } else {
        vec![PUPPET]
    }
}
fn closed_context(
    core: &CoreTestFixture,
    target: &str,
    roots: &[&str],
) -> Result<ProjectionContext> {
    let mut names = BTreeSet::new();
    let mut pending = roots.iter().map(|n| (*n).to_owned()).collect::<Vec<_>>();
    while let Some(name) = pending.pop() {
        let definition = core
            .features
            .0
            .get(&name)
            .ok_or_else(|| eyre::eyre!("unknown mixin owner: {name}"))?;
        ensure!(
            definition.supported_targets.iter().any(|id| id == target),
            "unsupported mixin owner: {name}"
        );
        if names.insert(name) {
            pending.extend(definition.requires.iter().cloned());
        }
    }
    core.context(
        target,
        &names.iter().map(String::as_str).collect::<Vec<_>>(),
    )
}
fn expected_rule(selected_source: Source) -> InputVariant {
    let mut when = InputPredicate::default();
    match class_name_or_resource(selected_source.path) {
        "EditBoxAccessor" => {
            when.targets = TARGETS[..2].iter().map(|s| (*s).to_owned()).collect();
            when.any_features = vec![SINGLE.to_owned(), TYPED.to_owned()];
        }
        "MouseHandlerMixin" => {
            when.any_features = vec![PUPPET.to_owned(), OVERLAY.to_owned(), POINTER.to_owned()];
        }
        "KeyboardHandlerMixin" => {
            when.targets = TARGETS[..2].iter().map(|s| (*s).to_owned()).collect();
            when.any_features = vec![KEYS.to_owned(), OVERLAY.to_owned()];
        }
        "MouseHandlerInvoker" | "KeyboardHandlerInvoker" => {
            when.targets = TARGETS[..2].iter().map(|s| (*s).to_owned()).collect();
            when.all_features = vec![PUPPET.to_owned()];
        }
        _ => {}
    }
    InputVariant {
        input: selected_source.path.to_owned(),
        when,
        template: selected_source.path == RESOURCE,
    }
}
fn class_name_or_resource(path: &str) -> &str {
    if path == RESOURCE {
        "sfm.mixins.json"
    } else {
        class_name(path)
    }
}
// The immutable ledger still uses expected_rule. Only the current accessor
// rule gains the independently selected document-history owner.
fn current_rule(selected_source: Source) -> InputVariant {
    let mut current = expected_rule(selected_source);
    // Java is always templated by the collector. Retain expected_rule as the
    // immutable historical metadata witness and check the exact current mode.
    current.template = true;
    if class_name_or_resource(selected_source.path) == "EditBoxAccessor" {
        current
            .when
            .any_features
            .push("document_history".to_owned());
    }
    current
}
fn verify_metadata(metadata: &CoreProjectInputs, selected_source: Source) -> Result<()> {
    ensure!(
        metadata.source_rules.get(selected_source.path)
            == Some(&vec![current_rule(selected_source)]),
        "mixin requires exact independent owner/target rule and JSON text mode"
    );
    Ok(())
}
fn expected_client_names(context: &ProjectionContext) -> Vec<String> {
    let mut result = Vec::new();
    let d2 = is_d2(target_id(context));
    let flags = &context.features;
    if d2 && (flags[SINGLE] || flags[TYPED] || flags["document_history"]) {
        result.push("EditBoxAccessor".to_owned());
    }
    if flags[PUPPET] || flags[OVERLAY] || flags[POINTER] {
        result.push("MouseHandlerMixin".to_owned());
    }
    if d2 && flags[PUPPET] {
        result.push("MouseHandlerInvoker".to_owned());
    }
    if d2 && (flags[KEYS] || flags[OVERLAY]) {
        result.push("KeyboardHandlerMixin".to_owned());
    }
    if d2 && flags[PUPPET] {
        result.push("KeyboardHandlerInvoker".to_owned());
    }
    result
}
fn expected_oid(path: &str, dev: bool, target: &str) -> Result<Option<&'static str>> {
    ensure!(TARGETS.contains(&target), "unknown frozen mixin target");
    if path == RESOURCE {
        return Ok(Some(if !dev && target == "26.1.2" {
            "e5a17eabd50c4c5fd49e07e2a9e189fdad872034"
        } else if !dev {
            "a4e7d758c662139d819e6ab031b1553dcb402684"
        } else if is_d2(target) {
            "490bd91c6590f0595bc1696f973878facd565539"
        } else if target == "26.1.2" {
            "db375db533741395a944058540944607e8421332"
        } else {
            "a0801d4819eb013530d61d3dfd15c6a8195b8cc4"
        }));
    }
    if !dev {
        return Ok(None);
    }
    Ok(match class_name(source(path)?.path) {
        "MouseHandlerMixin" => Some(if is_d2(target) {
            "643ea852e5cab170c4e8c39fe5af2e3e1cb289b0"
        } else if matches!(target, "1.20" | "1.20.1") {
            "b1ebd296ef3f8dcf4d084b8570acce3b021a2a8e"
        } else {
            "ba825c149ae9d855d4d2ee43698940fefc99dfe8"
        }),
        "EditBoxAccessor" if is_d2(target) => Some("8d0b4466929dc3fb03006cdbc1996a10b4590eb7"),
        "MouseHandlerInvoker" if is_d2(target) => Some("17e22857c0761e2c87922ead1ae53460c126ebee"),
        "KeyboardHandlerMixin" if is_d2(target) => Some("345209e2410d3b382ca46b284631d552aa8256cd"),
        "KeyboardHandlerInvoker" if is_d2(target) => {
            Some("e13e89eb58fdbfe161439410b81d6c3e8e3971ed")
        }
        _ => None,
    })
}
fn normalization_name(fixed: Golden) -> &'static str {
    if fixed.append_lf {
        "approved_resource_CRLF_to_LF_then_append_exactly_one_finalLF"
    } else if fixed.crlf > 0 {
        "approved_resource_CRLF_to_LF_only"
    } else {
        "raw_exact"
    }
}
fn normalize_raw(bytes: &[u8], fixed: Golden) -> Result<Vec<u8>> {
    ensure!(
        bytes.len() == fixed.raw_bytes && sha256(bytes) == fixed.raw_sha256,
        "mixin raw witness hash or length drift"
    );
    let text = std::str::from_utf8(bytes)?;
    ensure!(
        !text.starts_with('\u{feff}')
            && text.ends_with('\n') == fixed.raw_final_lf
            && text.matches("\r\n").count() == fixed.crlf
            && !text.replace("\r\n", "").contains('\r'),
        "mixin raw newline or BOM drift"
    );
    let mut normalized = text.replace("\r\n", "\n").into_bytes();
    if fixed.append_lf {
        ensure!(!fixed.raw_final_lf, "unapproved duplicate terminal LF");
        normalized.push(b'\n');
    }
    ensure!(
        normalized.len() == fixed.normalized_bytes
            && sha256(&normalized) == fixed.normalized_sha256,
        "mixin normalization exceeded exact approval"
    );
    Ok(normalized)
}
// Preserve the complete historical resource pin and all original raw/golden
// witnesses; recover it by reversing exactly the one reviewed current guard.
fn verify_current_template(bytes: &[u8], selected_source: Source) -> Result<()> {
    if selected_source.path == SOURCES[1].path || selected_source.path == SOURCES[3].path {
        let (size, digest) = if selected_source.path == SOURCES[1].path {
            (
                4198,
                "sha256:1fa8816cb01467c6667e0a377d0c6d433e13db391b67722df0e0b41aa4a631b5",
            )
        } else {
            (
                2671,
                "sha256:ae8f390a903ff0dfba174923845108eca89b128818f5df4a401685b31939afb0",
            )
        };
        ensure!(
            bytes.len() == size && sha256(bytes) == digest,
            "current ingress template drift"
        );
        let mut original = std::str::from_utf8(bytes)?.to_owned();
        let pair = "{% if features.pointer_modifier_ingress or features.client_overlay_input and features.client_overlay_scenes and features.workspace_panels %}";
        let direct = "{% if features.client_overlay_input and features.client_overlay_scenes and features.workspace_panels %}";
        if selected_source.path == SOURCES[1].path {
            ensure!(
                original.matches(pair).count() == 3,
                "pointer/overlay boundary count changed"
            );
            original = original.replace(
                pair,
                "{% if features.client_overlay_input or features.pointer_modifier_ingress %}",
            );
        }
        ensure!(
            original.matches(direct).count() == 3,
            "overlay boundary count changed"
        );
        original = original.replace(direct, "{% if features.client_overlay_input %}");
        return verify_template(original.as_bytes(), selected_source);
    }
    if selected_source.path != RESOURCE {
        return verify_template(bytes, selected_source);
    }
    ensure!(
        bytes.len() == 1625
            && sha256(bytes)
                == "sha256:56d025c4d4bc0a411bc20cdb136f080f1c372aeed5064e0f25c36cd9dc07fc83",
        "current mixin registration exceeded the one reviewed owner guard"
    );
    let text = std::str::from_utf8(bytes)?;
    let current = "{% if features.single_line_input or features.typed_command_palette or features.document_history %}";
    ensure!(
        text.matches(current).count() == 1,
        "current mixin guard is not unique"
    );
    let historical = text.replacen(
        current,
        "{% if features.single_line_input or features.typed_command_palette %}",
        1,
    );
    verify_template(historical.as_bytes(), selected_source)
}
fn verify_template(bytes: &[u8], selected_source: Source) -> Result<()> {
    ensure!(
        bytes.len() == selected_source.template_bytes
            && sha256(bytes) == selected_source.template_sha256
            && !bytes.contains(&b'\r')
            && bytes.ends_with(b"\n"),
        "mixin authored template drift"
    );
    std::str::from_utf8(bytes)?;
    Ok(())
}
fn write_fixture(root: &Path, relative: &str, bytes: &[u8]) -> Result<()> {
    let destination = root.join(relative);
    fs::create_dir_all(destination.parent().expect("fixed fixture parent"))?;
    fs::write(destination, bytes)?;
    Ok(())
}
#[test]
fn mixin_closure_preserves_all_twenty_frozen_source_and_registration_witnesses() -> Result<()> {
    let fixture = Fixture::load()?;
    let isolated = fixture.isolated()?;
    let mut counts = (0, 0);
    for (name, _) in COMMITS {
        let (environment, target) = name.split_once('/').expect("fixed context");
        let mut current_roots = witness_roots(environment, target);
        if current_roots.contains(&OVERLAY) {
            current_roots.extend(["client_overlay_scenes", "workspace_panels"]);
        }
        let context = closed_context(&fixture.core, target, &current_roots)?;
        let outputs = isolated.prepare(&context)?;
        fixture.verify_class_closure(&context, &outputs)?;
        for selected_source in SOURCES {
            if let Some(oid) = expected_oid(selected_source.path, environment == "dev", target)? {
                assert_eq!(
                    outputs[selected_source.path], fixture.normalized[oid],
                    "{} / {name}",
                    selected_source.path
                );
                counts.0 += 1;
            } else {
                assert!(!outputs.contains_key(selected_source.path));
                counts.1 += 1;
            }
        }
    }
    assert_eq!(counts, (38, 82));
    Ok(())
}
#[test]
fn mixin_closure_independent_ingress_masks_match_selected_classes_and_registration() -> Result<()> {
    let fixture = Fixture::load()?;
    let isolated = fixture.isolated()?;
    let mut masks = 0;
    for target in &TARGETS[..2] {
        for mask in 0..64u8 {
            let roots = OWNERS
                .into_iter()
                .enumerate()
                .filter_map(|(bit, name)| (mask & (1 << bit) != 0).then_some(name))
                .collect::<Vec<_>>();
            let context = closed_context(&fixture.core, target, &roots)?;
            let outputs = isolated.prepare(&context)?;
            fixture.verify_class_closure(&context, &outputs)?;
            let overlay_active = context.features[OVERLAY]
                && context.features["client_overlay_scenes"]
                && context.features["workspace_panels"];
            if let Some(bytes) = outputs.get(SOURCES[1].path) {
                let mouse = std::str::from_utf8(bytes)?;
                assert_eq!(mouse.contains("SFMClientOverlayRuntime"), overlay_active);
                assert_eq!(mouse.contains("routeSfmOverlayScroll"), overlay_active);
                assert_eq!(mouse.contains("observeSfmOverlayPointer"), overlay_active);
                assert_eq!(
                    mouse.contains("SFMPointerInputModifiers.begin(modifiers);"),
                    context.features[POINTER]
                );
                assert_eq!(
                    mouse.contains("finishSfmPointerModifiers"),
                    context.features[POINTER]
                );
                assert_eq!(
                    mouse.contains("catch (RuntimeException | Error failure)"),
                    context.features[POINTER] && overlay_active
                );
                assert_eq!(
                    mouse.contains("preventPuppetMouseGrab"),
                    context.features[PUPPET]
                );
                assert_eq!(
                    mouse.contains("import ca.teamdman.sfm.properties.SFMProperties;"),
                    context.features[PUPPET]
                );
                assert!(!mouse.contains("remap = false"));
                if context.features[POINTER] && overlay_active {
                    let cancel_cleanup =
                        "SFMPointerInputModifiers.end();\n                callback.cancel();";
                    assert!(mouse.contains(cancel_cleanup));
                    assert!(
                        mouse.contains(
                            "SFMPointerInputModifiers.end();\n            throw failure;"
                        )
                    );
                }
            }
            if let Some(bytes) = outputs.get(SOURCES[3].path) {
                let keyboard = std::str::from_utf8(bytes)?;
                assert_eq!(
                    keyboard.contains("onPreVanillaReservedKeyPressed"),
                    context.features[KEYS]
                );
                assert_eq!(keyboard.contains("keyFullscreen"), context.features[KEYS]);
                assert_eq!(keyboard.contains("keyScreenshot"), context.features[KEYS]);
                assert_eq!(
                    keyboard.contains("import org.lwjgl.glfw.GLFW;"),
                    context.features[KEYS]
                );
                assert_eq!(keyboard.contains("SFMClientOverlayRuntime"), overlay_active);
                assert_eq!(
                    keyboard.contains("handleSfmOverlayCharacter"),
                    overlay_active
                );
                if context.features[KEYS] && overlay_active {
                    assert!(
                        keyboard.find("SFMClientOverlayRuntime.get().key")
                            < keyboard.find("if (action != GLFW.GLFW_PRESS)")
                    );
                }
            }
            masks += 1;
        }
    }
    assert_eq!(masks, 128);
    let mut older_masks = 0;
    for target in &TARGETS[2..] {
        for mask in 0..4u8 {
            let roots = [PUPPET, KEYS]
                .into_iter()
                .enumerate()
                .filter_map(|(bit, name)| (mask & (1 << bit) != 0).then_some(name))
                .collect::<Vec<_>>();
            let context = closed_context(&fixture.core, target, &roots)?;
            let outputs = isolated.prepare(&context)?;
            fixture.verify_class_closure(&context, &outputs)?;
            if let Some(mouse) = outputs.get(SOURCES[1].path) {
                assert_eq!(
                    *mouse,
                    fixture.normalized[expected_oid(SOURCES[1].path, true, target)?
                        .expect("puppet mouse source")]
                );
                let text = std::str::from_utf8(mouse)?;
                assert_eq!(
                    text.contains("remap = false"),
                    !matches!(*target, "1.20" | "1.20.1")
                );
                assert!(!text.contains("SFMClientOverlayRuntime"));
                assert!(!text.contains("SFMPointerInputModifiers"));
            }
            for selected_source in [SOURCES[0], SOURCES[2], SOURCES[3], SOURCES[4]] {
                assert!(!outputs.contains_key(selected_source.path));
            }
            older_masks += 1;
        }
        for owner in [SINGLE, TYPED, OVERLAY, POINTER] {
            assert!(closed_context(&fixture.core, target, &[owner]).is_err());
        }
    }
    assert_eq!(older_masks, 32);
    for target in &TARGETS[..2] {
        for mask in 0..8 {
            let roots = [OVERLAY, "client_overlay_scenes", "workspace_panels"]
                .into_iter()
                .enumerate()
                .filter_map(|(bit, owner)| (mask & (1 << bit) != 0).then_some(owner))
                .collect::<Vec<_>>();
            let context = closed_context(&fixture.core, target, &roots)?;
            let outputs = isolated.prepare(&context)?;
            fixture.verify_class_closure(&context, &outputs)?;
            for selected_source in [SOURCES[1], SOURCES[3]] {
                let body = outputs
                    .get(selected_source.path)
                    .map(|bytes| std::str::from_utf8(bytes))
                    .transpose()?;
                assert_eq!(body.is_some(), mask & 1 != 0);
                assert_eq!(
                    body.is_some_and(|body| body.contains("SFMClientOverlayRuntime")),
                    mask == 7
                );
            }
            assert!(!context.features[POINTER] && !context.features[PUPPET]);
        }
    }
    for owner in [PUPPET, KEYS, TYPED] {
        let full = closed_context(&fixture.core, "1.19.2", &[owner])?;
        for required in &fixture.core.features.0[owner].requires {
            let missing = full
                .features
                .iter()
                .filter(|(id, on)| **on && *id != required)
                .map(|(id, _)| id.as_str())
                .collect::<Vec<_>>();
            assert!(
                fixture.core.context("1.19.2", &missing).is_err(),
                "real prerequisite silently bypassed"
            );
        }
    }
    for owner in [SINGLE, OVERLAY, POINTER] {
        assert!(fixture.core.features.0[owner].requires.is_empty());
    }
    Ok(())
}
#[test]
fn mixin_closure_membership_depends_on_features_and_mc_not_environment_or_key() -> Result<()> {
    let fixture = Fixture::load()?;
    let isolated = fixture.isolated()?;
    for target in TARGETS {
        for roots in [vec![], vec![PUPPET]] {
            let context = closed_context(&fixture.core, target, &roots)?;
            let expected = isolated.prepare(&context)?;
            let mut renamed = context.clone();
            renamed.environment = if context.environment == "release" {
                "dev"
            } else {
                "release"
            }
            .to_owned();
            renamed.projection_key = "arbitrary/nested/mixin-feature-proof".to_owned();
            renamed.preset = renamed.projection_key.clone();
            assert_eq!(isolated.prepare(&renamed)?, expected);
            fixture.verify_class_closure(&renamed, &expected)?;
        }
    }
    Ok(())
}
#[test]
fn mixin_closure_common_edits_propagate_through_shared_text_and_java() -> Result<()> {
    let fixture = Fixture::load()?;
    let isolated = fixture.isolated()?;
    let resource = read_bounded(&checked_file(&fixture.core.core, RESOURCE)?, 1024 * 1024)?;
    let original = std::str::from_utf8(&resource)?;
    let changed = original.replacen("\"minVersion\": \"0.8.3\"", "\"minVersion\": \"0.8.4\"", 1);
    assert_ne!(changed, original);
    write_fixture(&isolated.root, RESOURCE, changed.as_bytes())?;
    let mut mouse = b"// isolated shared mixin edit\n".to_vec();
    mouse.extend_from_slice(&read_bounded(
        &checked_file(&fixture.core.core, SOURCES[1].path)?,
        1024 * 1024,
    )?);
    write_fixture(&isolated.root, SOURCES[1].path, &mouse)?;
    for target in TARGETS {
        let context = closed_context(&fixture.core, target, &[PUPPET])?;
        let outputs = isolated.prepare(&context)?;
        let registration: Registration =
            facet_json::from_str(std::str::from_utf8(&outputs[RESOURCE])?)?;
        assert_eq!(registration.min_version, "0.8.4");
        let mut expected = b"// isolated shared mixin edit\n".to_vec();
        let oid = expected_oid(
            SOURCES[1].path,
            true,
            if is_d2(target) { "1.20" } else { target },
        )?
        .expect("mouse source");
        expected.extend_from_slice(&fixture.normalized[oid]);
        assert_eq!(outputs[SOURCES[1].path], expected, "shared edit / {target}");
    }
    Ok(())
}
#[test]
fn mixin_closure_hash_mode_path_context_and_inactive_source_mutations_fail_closed() -> Result<()> {
    let fixture = Fixture::load()?;
    for fixed in GOLDENS {
        let mut changed = fixture.raw[fixed.oid].clone();
        changed.push(b' ');
        assert!(normalize_raw(&changed, fixed).is_err());
        let mut changed_contract = fixed;
        changed_contract.crlf += 1;
        assert!(normalize_raw(&fixture.raw[fixed.oid], changed_contract).is_err());
        changed_contract = fixed;
        changed_contract.append_lf = !fixed.append_lf;
        assert!(normalize_raw(&fixture.raw[fixed.oid], changed_contract).is_err());
    }
    let mut altered = fixture.core.read_source(SOURCES[0].path)?;
    altered.push(b' ');
    assert!(verify_template(&altered, SOURCES[0]).is_err());
    assert!(source("src/../elsewhere.java").is_err());
    assert!(golden("0000000000000000000000000000000000000000").is_err());
    assert!(closed_context(&fixture.core, "1.19.2", &["unknown_mixin_owner"]).is_err());
    let context = closed_context(&fixture.core, "1.19.2", &[])?;
    let mut metadata = fixture.core.metadata.clone();
    metadata
        .source_rules
        .get_mut(RESOURCE)
        .expect("registered JSON rule")[0]
        .template = false;
    assert!(verify_metadata(&metadata, source(RESOURCE)?).is_err());
    metadata = fixture.core.metadata.clone();
    let duplicate = metadata.source_rules[RESOURCE][0].clone();
    metadata
        .source_rules
        .get_mut(RESOURCE)
        .expect("registered JSON rule")
        .push(duplicate);
    assert!(select_core_inputs(&metadata, &context, &fixture.inventory).is_err());
    metadata = fixture.core.metadata.clone();
    metadata
        .source_rules
        .get_mut(RESOURCE)
        .expect("registered JSON rule")[0]
        .input = "src/../unowned.json".to_owned();
    assert!(
        metadata
            .validate(&fixture.core.features.registered_names())
            .is_err()
    );
    let isolated = fixture.isolated()?;
    isolated.prepare(&context)?;
    write_fixture(&isolated.root, SOURCES[1].path, b"\xffinactive-not-Java")?;
    let release = isolated.prepare(&context)?;
    assert!(
        !release.contains_key(SOURCES[1].path),
        "omitted source read or rendered"
    );
    let active = closed_context(&fixture.core, "1.19.2", &[PUPPET])?;
    assert!(
        isolated.prepare(&active).is_err(),
        "active malformed Java accepted"
    );
    write_fixture(
        &isolated.root,
        SOURCES[1].path,
        &read_bounded(
            &checked_file(&fixture.core.core, SOURCES[1].path)?,
            1024 * 1024,
        )?,
    )?;
    let inventory = discover_core_source_files(&isolated.root)?;
    let selection = select_core_inputs(&isolated.metadata, &context, &inventory)?;
    assert!(
        collect_core_artifacts(&isolated.root, &selection, &active).is_err(),
        "selection context drift accepted"
    );
    Ok(())
}
