//! Prepared source-boundary regressions; run only after reviewed promotion.
//!
//! This module uses real selection, rendering and collection APIs. It does not
//! execute Java, pointer callbacks, OS input or a Minecraft/client UI.

#![cfg(test)]

use super::candidate_lock::checked_file;
use super::context::ProjectionContext;
use super::core_catalog::CoreCatalog;
use super::core_inputs::CORE_ROOT;
use super::core_inputs::collect_core_artifacts;
use super::core_inputs::discover_core_source_files;
use super::core_inputs::select_core_inputs;
use super::core_slice_test_support::CoreTestFixture;
use super::core_slice_test_support::read_bounded;
use super::core_slice_test_support::read_git_blobs;
use super::provenance::sha256;
use super::render_java_source;
use eyre::Result;
use eyre::ensure;
use facet::Facet;
use std::collections::BTreeMap;
use std::collections::BTreeSet;

const PATH: &str = "src/main/java/ca/teamdman/sfm/client/input/SFMPointerInputModifiers.java";
const OWNER: &str = "pointer_modifier_ingress";
const OID: &str = "593ea943db5339952631dfdcf932e5e4bf32cd06";
const DIGEST: &str = "sha256:d496c3f8885228b58087e03c44b5bfafa19e1e4b014b7d1ed0c1fd6a4ea8570b";
const LEDGER: &str = "docs/tasks/sfm-core-pointer-input-modifiers-slice.json";
const MOUSE: &str = "src/main/java/ca/teamdman/sfm/mixins/MouseHandlerMixin.java";
const MULTIPLEXER: &str =
    "src/main/java/ca/teamdman/sfm/client/screen/workspace/SFMScreenMultiplexer.java";
const TARGETS: [&str; 10] = [
    "1.19.2", "1.19.4", "1.20", "1.20.1", "1.20.2", "1.20.3", "1.20.4", "1.21.0", "1.21.1",
    "26.1.2",
];
const PROJECT_FILES: [&str; 8] = [
    "build.gradle",
    "settings.gradle",
    "gradle.properties",
    "gradlew",
    "gradlew.bat",
    "sfm-toolchain.lock.json",
    "gradle/wrapper/gradle-wrapper.properties",
    "gradle/wrapper/gradle-wrapper.jar",
];
const BANNER: &str =
    "// GENERATED by sfm-propagate-changes; edit the primary source or reconcile this file.\n";
const COMMITS: [(&str, &str); 20] = [
    ("dev/1.19.2", "f3ff2f6425434f36c7c680fa909c977b158e1860"),
    ("dev/1.19.4", "2e3b561c15d663fb89fd353ccc2af67eeb0c2053"),
    ("dev/1.20", "6bf4845761d06560fc5e0e36018b5d583589004d"),
    ("dev/1.20.1", "faa040ce14dd825f2dd9716ea59508bf46278c06"),
    ("dev/1.20.2", "a829fb4db2ae06eddd2defb22e33f0b45a4b3ff9"),
    ("dev/1.20.3", "704aa69edad5376d8d6cfb0b0ef7845af077e647"),
    ("dev/1.20.4", "11d3ed07d654ff801329f17cf1eb81c2b347eecd"),
    ("dev/1.21.0", "43068d610b1c053c6569be486439769eec2ae9ef"),
    ("dev/1.21.1", "7524ab5512878b773e212600c9578b2bc4db4717"),
    ("dev/26.1.2", "6bd27f03863ddd041344cbc3da51b01a7b3c3e1f"),
    ("release/1.19.2", "31135b8e86801b862d5cb2283c7c5878b7cc5bb4"),
    ("release/1.19.4", "23785b63e3e1fe35e5be6a6d89b6638ee0ff0daa"),
    ("release/1.20", "3df18123a19535fd0e5d1dc81aa302105c3fd2f6"),
    ("release/1.20.1", "bb5babf12f467235b3a44ad5098666ee3ed171ec"),
    ("release/1.20.2", "cfbbafaeda4a006ae32743a92de330711983056b"),
    ("release/1.20.3", "1b7f9605da0ef13c7601daf3786545868dfc3c78"),
    ("release/1.20.4", "a637581b5e1078d7cc0ca68333add568e3e387ff"),
    ("release/1.21.0", "6bfab8a21e7a5bbeb0bb136bf4e5b26f6ce03e25"),
    ("release/1.21.1", "f5366c79c823ff52712130e69dd9c8166c70bd14"),
    ("release/26.1.2", "fe32b29453b13b4f3050ad441677c7eb79e80814"),
];

#[derive(Facet)]
struct Ledger {
    schema: String,
    context_commits: BTreeMap<String, String>,
    normalization: String,
    files: Vec<Leaf>,
}
#[derive(Facet)]
struct Leaf {
    path: String,
    core_path: String,
    template_sha256: String,
    template_bytes: usize,
    raw_blob: String,
    raw_sha256: String,
    raw_bytes: usize,
    line_endings: String,
    terminal_newline: String,
    normalization: String,
    membership: Membership,
    witnesses: Vec<Witness>,
}
#[derive(Facet)]
struct Membership {
    targets: Vec<String>,
    all_features: Vec<String>,
    any_features: Vec<String>,
    none_features: Vec<String>,
}
#[derive(Facet)]
struct Witness {
    context: String,
    source_commit: String,
    present: bool,
    raw_blob: Option<String>,
    raw_sha256: Option<String>,
    raw_bytes: Option<usize>,
    mode: Option<String>,
    explicit_registered_features: Vec<String>,
}
struct Fixture {
    core: CoreTestFixture,
    inventory: BTreeSet<String>,
    raw: Vec<u8>,
}

fn same(actual: &[String], expected: &[&str]) -> bool {
    actual.len() == expected.len()
        && actual.iter().map(String::as_str).collect::<BTreeSet<_>>()
            == expected.iter().copied().collect()
}
fn is_d2(target: &str) -> bool {
    matches!(target, "1.19.2" | "1.19.4")
}
fn pinned_commits() -> BTreeMap<String, String> {
    COMMITS
        .into_iter()
        .map(|(key, oid)| (key.to_owned(), oid.to_owned()))
        .collect()
}
fn validate_raw(bytes: &[u8]) -> Result<()> {
    ensure!(
        bytes.len() == 1143
            && sha256(bytes) == DIGEST
            && !bytes.contains(&b'\r')
            && bytes.ends_with(b"\n")
            && !bytes.ends_with(b"\n\n"),
        "pointer raw bytes or exact LF contract changed"
    );
    std::str::from_utf8(bytes)?;
    Ok(())
}
impl Fixture {
    fn load() -> Result<Self> {
        let core = CoreTestFixture::load()?;
        let ledger: Ledger = facet_json::from_str(std::str::from_utf8(&read_bounded(
            &checked_file(&core.repository, LEDGER)?,
            1024 * 1024,
        )?)?)?;
        ensure!(
            ledger.schema == "sfm:core_pointer_input_modifiers_slice@1"
                && ledger.context_commits == pinned_commits()
                && ledger.normalization == "none_raw_exact_lf_with_exactly_one_terminal_lf"
                && ledger.files.len() == 1,
            "pointer ledger scope changed"
        );
        let leaf = ledger.files.into_iter().next().expect("checked sole leaf");
        ensure!(
            leaf.path == PATH
                && leaf.core_path == format!("{CORE_ROOT}/{PATH}")
                && leaf.template_sha256 == DIGEST
                && leaf.template_bytes == 1143
                && leaf.raw_blob == OID
                && leaf.raw_sha256 == DIGEST
                && leaf.raw_bytes == 1143
                && leaf.line_endings == "lf"
                && leaf.terminal_newline == "exactly_one_lf"
                && leaf.normalization == "none"
                && same(&leaf.membership.targets, &TARGETS[..2])
                && same(&leaf.membership.all_features, &[OWNER])
                && leaf.membership.any_features.is_empty()
                && leaf.membership.none_features.is_empty(),
            "pointer ledger raw contract changed"
        );
        ensure!(leaf.witnesses.len() == 20, "pointer witness count changed");
        let commits = pinned_commits();
        let mut seen = BTreeSet::new();
        let mut cells = (0, 0);
        for witness in leaf.witnesses {
            let (environment, target) = witness
                .context
                .split_once('/')
                .ok_or_else(|| eyre::eyre!("malformed pointer frozen context"))?;
            let present = environment == "dev" && is_d2(target);
            ensure!(
                seen.insert(witness.context.clone())
                    && commits.get(&witness.context) == Some(&witness.source_commit)
                    && witness.present == present
                    && witness.raw_blob.as_deref() == present.then_some(OID)
                    && witness.raw_sha256.as_deref() == present.then_some(DIGEST)
                    && witness.raw_bytes == present.then_some(1143)
                    && witness.mode.as_deref() == present.then_some("100644")
                    && same(
                        &witness.explicit_registered_features,
                        if present { &[OWNER] } else { &[] },
                    ),
                "pointer frozen witness changed"
            );
            if present {
                cells.0 += 1;
            } else {
                cells.1 += 1;
            }
        }
        ensure!(
            seen == commits.keys().cloned().collect() && cells == (2, 18),
            "pointer context coverage changed"
        );
        let rules = core
            .metadata
            .source_rules
            .get(PATH)
            .ok_or_else(|| eyre::eyre!("pointer rule is not promoted"))?;
        ensure!(
            rules.len() == 1
                && rules[0].input == PATH
                && rules[0].template
                && same(&rules[0].when.targets, &TARGETS[..2])
                && same(&rules[0].when.all_features, &[OWNER])
                && rules[0].when.any_features.is_empty()
                && rules[0].when.none_features.is_empty(),
            "pointer metadata ownership changed"
        );
        let blobs = read_git_blobs(&core.repository, &BTreeSet::from([OID.to_owned()]))?;
        let raw = blobs.get(OID).expect("requested pointer blob").clone();
        validate_raw(&raw)?;
        let authored = core.read_source(PATH)?;
        validate_raw(&authored)?;
        ensure!(
            authored == raw,
            "pointer template is not the genuine raw source"
        );
        let inventory = discover_core_source_files(&core.core)?;
        ensure!(inventory.contains(PATH), "pointer source is not promoted");
        Ok(Self {
            core,
            inventory,
            raw,
        })
    }

    fn render(&self, context: &ProjectionContext) -> Result<Option<Vec<u8>>> {
        let selection = self
            .core
            .selection_for_assertion(context, &self.inventory)?;
        let Some(input) = selection.inputs.get(PATH) else {
            ensure!(
                selection.omitted_paths.contains(PATH),
                "pointer omission lacks a predicate"
            );
            return Ok(None);
        };
        ensure!(
            input.input == PATH && input.template,
            "pointer selected an alternate input"
        );
        let source = self.core.read_source(PATH)?;
        validate_raw(&source)?;
        Ok(Some(
            render_java_source(std::str::from_utf8(&source)?, context)?.into_bytes(),
        ))
    }
}

#[test]
fn pointer_ledger_and_raw_body_bind_one_genuine_twenty_cell_source() -> Result<()> {
    let fixture = Fixture::load()?;
    assert_eq!(fixture.raw.len(), 1143);
    assert_eq!(sha256(&fixture.raw), DIGEST);
    assert_eq!(pinned_commits().len(), 20);
    let owner = &fixture.core.features.0[OWNER];
    assert!(same(&owner.supported_targets, &TARGETS[..2]));
    assert!(owner.requires.is_empty());
    Ok(())
}

#[test]
fn pointer_twenty_historical_contexts_reconstruct_two_present_eighteen_absent() -> Result<()> {
    let fixture = Fixture::load()?;
    let mut cells = (0, 0);
    for (name, _) in COMMITS {
        let (environment, target) = name.split_once('/').expect("fixed context");
        let present = environment == "dev" && is_d2(target);
        let context = fixture
            .core
            .context(target, if present { &[OWNER] } else { &[] })?;
        assert_eq!(
            fixture.render(&context)?.as_deref(),
            present.then_some(fixture.raw.as_slice())
        );
        if present {
            cells.0 += 1;
        } else {
            cells.1 += 1;
        }
    }
    assert_eq!(cells, (2, 18));
    Ok(())
}

#[test]
fn pointer_twenty_feature_off_controls_omit_before_selected_source_read() -> Result<()> {
    let mut fixture = Fixture::load()?;
    let catalog = CoreCatalog::load(&fixture.core.repository, &fixture.core.repository)?;
    assert_eq!(catalog.catalog.0.len(), 20);
    fixture.core.core = fixture
        .core
        .core
        .join("deliberately_missing_pointer_source_boundary");
    for key in catalog.catalog.0.keys() {
        let context = fixture.core.historical_feature_off_catalog_context(key)?;
        assert!(
            !context.features[OWNER],
            "unexpected historical control owner admission: {key}"
        );
        assert!(fixture.render(&context)?.is_none());
    }
    Ok(())
}

#[test]
fn pointer_owner_toggles_independently_from_unrelated_existing_features() -> Result<()> {
    let fixture = Fixture::load()?;
    let mut masks = 0;
    for target in &TARGETS[..2] {
        for mask in 0_u8..8 {
            let mut enabled = Vec::new();
            for (index, owner) in [OWNER, "workspace_panels", "client_overlay_input"]
                .iter()
                .enumerate()
            {
                if mask & (1 << index) != 0 {
                    enabled.push(*owner);
                }
            }
            let context = fixture.core.context(target, &enabled)?;
            assert_eq!(
                fixture.render(&context)?.as_deref(),
                (mask & 1 != 0).then_some(fixture.raw.as_slice()),
            );
            let selected =
                select_core_inputs(&fixture.core.metadata, &context, &fixture.inventory)?;
            if let Some(input) = selected.inputs.get(PATH) {
                assert_eq!(input.input, PATH);
                assert!(input.template);
            }
            assert!(!context.features["workspace_panel_move_gestures"]);
            masks += 1;
        }
    }
    assert_eq!(masks, 16);
    Ok(())
}

#[test]
fn pointer_unsupported_targets_and_existing_move_prerequisites_fail_closed() -> Result<()> {
    let fixture = Fixture::load()?;
    let move_feature = &fixture.core.features.0["workspace_panel_move_gestures"];
    assert!(same(&move_feature.supported_targets, &TARGETS[..2]));
    assert!(same(
        &move_feature.requires,
        &["workspace_panel_entry_controls", OWNER],
    ));
    for target in &TARGETS[2..] {
        assert!(fixture.core.context(target, &[OWNER]).is_err());
        let off = fixture.core.context(target, &[])?;
        assert!(fixture.render(&off)?.is_none());
    }
    for target in &TARGETS[..2] {
        assert!(
            fixture
                .core
                .context(target, &["workspace_panel_move_gestures"])
                .is_err()
        );
        assert!(
            fixture
                .core
                .context(target, &["workspace_panel_move_gestures", OWNER])
                .is_err()
        );
    }
    Ok(())
}

#[test]
fn pointer_environment_key_and_preset_are_not_whole_file_dispatchers() -> Result<()> {
    let fixture = Fixture::load()?;
    for target in &TARGETS[..2] {
        for environment in ["release", "dev", "review"] {
            for enabled in [false, true] {
                let mut context = fixture
                    .core
                    .context(target, if enabled { &[OWNER] } else { &[] })?;
                context.environment = environment.to_owned();
                context.projection_key = format!("review/pointer/{environment}/{target}");
                context.preset = "not_a_feature_or_version_selector".to_owned();
                assert_eq!(
                    fixture.render(&context)?.as_deref(),
                    enabled.then_some(fixture.raw.as_slice()),
                );
            }
        }
    }
    Ok(())
}

#[test]
fn pointer_actual_caller_guards_and_threadlocal_restoration_source_contract_remain() -> Result<()> {
    let fixture = Fixture::load()?;
    let body = std::str::from_utf8(&fixture.raw)?;
    for marker in [
        "private static final ThreadLocal<Integer> CURRENT = new ThreadLocal<>();",
        "public static void begin(int modifiers) { CURRENT.set(modifiers); }",
        "public static void end() { CURRENT.remove(); }",
        "value == null ? OptionalInt.empty() : OptionalInt.of(value)",
        "value == null ? physicalFallback.getAsBoolean() : (value & mask) != 0",
        "Integer previous = CURRENT.get();",
        "try { return operation.get(); }",
        "finally { if (previous == null) end(); else begin(previous); }",
    ] {
        assert!(
            body.contains(marker),
            "genuine pointer contract changed: {marker}"
        );
    }
    for forbidden in [
        "net.minecraft.",
        "org.lwjgl.",
        "java.nio.file.",
        "ProcessBuilder",
        "SFMPacket",
    ] {
        assert!(
            !body.contains(forbidden),
            "pointer leaf gained an external/effect dependency"
        );
    }
    let mouse = String::from_utf8(fixture.core.read_source(MOUSE)?)?;
    let multiplexer = String::from_utf8(fixture.core.read_source(MULTIPLEXER)?)?;
    let begin = mouse
        .find("SFMPointerInputModifiers.begin(modifiers)")
        .expect("actual ingress");
    let gate = mouse[..begin]
        .rfind("{% if features.pointer_modifier_ingress %}")
        .expect("actual ingress owner gate");
    assert!(!mouse[gate..begin].contains("{% endif %}"));
    let call = multiplexer
        .find("ca.teamdman.sfm.client.input.SFMPointerInputModifiers.isDown(")
        .expect("actual workspace caller");
    let move_gate = multiplexer[..call]
        .rfind("{% if features.workspace_panel_move_gestures %}")
        .expect("actual move owner gate");
    assert!(!multiplexer[move_gate..call].contains("{% endif %}"));
    assert!(multiplexer[call..].starts_with(
        "ca.teamdman.sfm.client.input.SFMPointerInputModifiers.isDown(\n                                GLFW.GLFW_MOD_ALT, Screen::hasAltDown)"
    ));
    for target in &TARGETS[..2] {
        for mask in 0_u8..16 {
            let mut enabled = Vec::new();
            if mask & 1 != 0 {
                enabled.push(OWNER);
            }
            if mask & 2 != 0 {
                enabled.push("client_overlay_input");
            }
            if mask & 4 != 0 {
                enabled.push("client_overlay_scenes");
            }
            if mask & 8 != 0 {
                enabled.push("workspace_panels");
            }
            let context = fixture.core.context(target, &enabled)?;
            let rendered = render_java_source(&mouse, &context)?;
            assert_eq!(
                rendered.contains("SFMPointerInputModifiers.begin("),
                mask & 1 != 0
            );
            assert_eq!(
                rendered.contains("SFMPointerInputModifiers.end()"),
                mask & 1 != 0
            );
            assert_eq!(
                rendered.contains("SFMClientOverlayRuntime.get().mouseButton("),
                mask & 14 == 14
            );
            assert_eq!(
                rendered.contains("finishSfmPointerModifiers("),
                mask & 1 != 0
            );
            if mask == 15 {
                assert!(rendered.contains("catch (RuntimeException | Error failure)"));
                assert!(rendered.contains("callback.cancel();"));
            }
        }
    }
    Ok(())
}

#[test]
fn pointer_real_collector_ignores_poison_when_off_and_emits_owned_bannered_body_when_on()
-> Result<()> {
    let fixture = Fixture::load()?;
    let temp = tempfile::tempdir()?;
    let core_root = temp.path().join(CORE_ROOT);
    std::fs::create_dir_all(&core_root)?;
    let mut metadata = fixture.core.metadata.clone();
    metadata.source_rules.retain(|path, _| path == PATH);
    let inventory = BTreeSet::from([PATH.to_owned()]);
    // A real edit of the one shared authored body must reach both D2 outputs.
    let common_source_edit = format!(
        "// shared pointer core propagation witness\n{}",
        std::str::from_utf8(&fixture.raw)?,
    );
    for target in &TARGETS[..2] {
        let off = fixture.core.context(target, &[])?;
        let off_selection = select_core_inputs(&metadata, &off, &inventory)?;
        assert!(!off_selection.inputs.contains_key(PATH));
        for (output, input) in &off_selection.inputs {
            ensure!(
                !output.starts_with("src/"),
                "unexpected isolated Java input"
            );
            let source = read_bounded(
                &checked_file(&fixture.core.core, &input.input)?,
                16 * 1024 * 1024,
            )?;
            let destination = core_root.join(&input.input);
            std::fs::create_dir_all(destination.parent().expect("portable project input"))?;
            std::fs::write(destination, source)?;
        }
        let destination = core_root.join(PATH);
        std::fs::create_dir_all(destination.parent().expect("portable source input"))?;
        std::fs::write(&destination, [0xff, 0xfe])?;
        let off_artifacts = collect_core_artifacts(&core_root, &off_selection, &off)?;
        assert!(!off_artifacts.contains_key(PATH));
        for output in PROJECT_FILES {
            assert!(off_artifacts.contains_key(output));
        }
        let on = fixture.core.context(target, &[OWNER])?;
        let on_selection = select_core_inputs(&metadata, &on, &inventory)?;
        assert!(on_selection.inputs[PATH].template);
        assert!(collect_core_artifacts(&core_root, &on_selection, &on).is_err());
        std::fs::write(&destination, &fixture.raw)?;
        let artifacts = collect_core_artifacts(&core_root, &on_selection, &on)?;
        let artifact = &artifacts[PATH];
        let rendered = render_java_source(std::str::from_utf8(&fixture.raw)?, &on)?;
        assert_eq!(artifact.source_bytes, fixture.raw);
        assert_eq!(artifact.source_path, format!("{CORE_ROOT}/{PATH}"));
        assert!(artifact.overlay.is_none());
        assert_eq!(
            artifact.output_bytes,
            format!("{BANNER}{rendered}").as_bytes()
        );
        assert_eq!(std::fs::read(&destination)?, fixture.raw);
        std::fs::write(&destination, common_source_edit.as_bytes())?;
        let changed = collect_core_artifacts(&core_root, &on_selection, &on)?;
        let changed_pointer = &changed[PATH];
        let changed_rendered = render_java_source(&common_source_edit, &on)?;
        assert_eq!(changed_pointer.source_bytes, common_source_edit.as_bytes());
        assert_eq!(changed_pointer.source_path, format!("{CORE_ROOT}/{PATH}"));
        assert!(changed_pointer.overlay.is_none());
        assert_eq!(
            changed_pointer.output_bytes,
            format!("{BANNER}{changed_rendered}").as_bytes(),
        );
        assert!(changed_rendered.starts_with("// shared pointer core propagation witness\n"));
        // Only the temp collector input was changed, never canonical core/history.
        assert_eq!(fixture.core.read_source(PATH)?, fixture.raw);
        std::fs::write(&destination, &fixture.raw)?;
    }
    Ok(())
}
