//! Collect one deterministic source tree before the guarded sync stage writes it.

use super::context::ProjectionContext;
use super::render_java_source;
use super::sync::ProjectedArtifact;
use eyre::Result;
use eyre::WrapErr;
use eyre::bail;
use eyre::ensure;
use std::collections::BTreeMap;
use std::collections::BTreeSet;
use std::fs;
use std::path::Component;
use std::path::Path;
use std::path::PathBuf;
use walkdir::WalkDir;

const UTF8_BOM: &[u8] = b"\xEF\xBB\xBF";
const GENERATED_BANNER: &str =
    "// GENERATED by sfm-propagate-changes; edit the primary source or reconcile this file.";

/// Select shared `src` files, then apply explicitly ordered version overlays.
///
/// Output keys and provenance paths use portable `src/...` paths. An overlay
/// replaces only the exact same output path; differently cased paths and
/// file/directory conflicts fail rather than depending on the host filesystem.
/// Java inputs pass through the controlled directive renderer and receive a
/// generated-file banner; all other inputs retain their exact bytes. Exclusions
/// use the canonical generated `src/...` output paths also used by manifest
/// `PathEffect.output_path`.
///
/// # Errors
///
/// Returns an error for missing or unsafe source roots, non-portable or
/// colliding output paths, invalid UTF-8 Java, or failed directive rendering.
pub fn collect_projected_inputs(
    primary_src_root: &Path,
    overlay_src_roots: &[(String, PathBuf)],
    context: &ProjectionContext,
    excluded_relative_paths: &BTreeSet<String>,
) -> Result<BTreeMap<String, ProjectedArtifact>> {
    collect_projected_inputs_with_allowlist(
        primary_src_root,
        overlay_src_roots,
        context,
        excluded_relative_paths,
        None,
    )
}

/// Collect selected source files while masking non-members before Java
/// rendering. Release presets use this to avoid parsing development-only Java
/// that is deliberately absent from the pinned tag's source tree.
///
/// # Errors
///
/// Returns an error for unsafe or invalid selected inputs.
pub fn collect_projected_inputs_with_allowlist(
    primary_src_root: &Path,
    overlay_src_roots: &[(String, PathBuf)],
    context: &ProjectionContext,
    excluded_relative_paths: &BTreeSet<String>,
    allowed_output_paths: Option<&BTreeSet<String>>,
) -> Result<BTreeMap<String, ProjectedArtifact>> {
    let excluded = normalize_exclusions(excluded_relative_paths)?;
    let mut artifacts = BTreeMap::new();
    let mut canonical_case = BTreeMap::<String, String>::new();

    collect_root(
        primary_src_root,
        None,
        &excluded,
        allowed_output_paths,
        &mut canonical_case,
        &mut artifacts,
    )?;

    let mut overlay_names = BTreeSet::new();
    for (name, root) in overlay_src_roots {
        validate_overlay_name(name)?;
        ensure!(
            overlay_names.insert(name),
            "duplicate source overlay name '{name}'"
        );
        collect_root(
            root,
            Some(name),
            &excluded,
            allowed_output_paths,
            &mut canonical_case,
            &mut artifacts,
        )?;
    }

    validate_no_output_collisions(&artifacts.keys().cloned().collect())?;

    // Render only the selected source. An overlay can intentionally replace
    // Java that cannot compile or project for this target.
    for (output_path, artifact) in &mut artifacts {
        render_java_artifact(output_path, artifact, context)?;
    }

    Ok(artifacts)
}

/// Replace selected output paths with files named explicitly by feature
/// Include/Replace effects. `explicit_inputs` maps canonical `src/...` output
/// paths to repository-relative input paths. The caller resolves effect kind
/// and priority; this function enforces filesystem and rendering safety.
///
/// # Errors
///
/// Returns an error for invalid paths, symlinks, sources outside the repository,
/// output collisions, or Java rendering failures. No artifacts are changed on
/// failure.
pub fn apply_explicit_inputs(
    repo_root: &Path,
    artifacts: &mut BTreeMap<String, ProjectedArtifact>,
    explicit_inputs: &BTreeMap<String, String>,
    context: &ProjectionContext,
) -> Result<()> {
    let root_metadata = fs::symlink_metadata(repo_root)
        .wrap_err_with(|| format!("cannot inspect repository root '{}'", repo_root.display()))?;
    ensure!(
        root_metadata.is_dir() && !root_metadata.file_type().is_symlink(),
        "repository root '{}' must be a real directory",
        repo_root.display()
    );
    let canonical_root = fs::canonicalize(repo_root)
        .wrap_err_with(|| format!("cannot resolve repository root '{}'", repo_root.display()))?;

    let mut known_case: BTreeMap<String, String> = artifacts
        .keys()
        .map(|path| (path.to_ascii_lowercase(), path.clone()))
        .collect();
    let mut pending = BTreeMap::new();
    for (output_path, input_path) in explicit_inputs {
        let relative_output = output_path.strip_prefix("src/").ok_or_else(|| {
            eyre::eyre!("explicit output '{output_path}' must be a canonical src/... path")
        })?;
        validate_portable_path(relative_output)?;
        validate_portable_path(input_path)?;
        let case_key = output_path.to_ascii_lowercase();
        if let Some(existing) = known_case.get(&case_key) {
            ensure!(
                existing == output_path,
                "case-colliding projected paths '{existing}' and '{output_path}'"
            );
        } else {
            known_case.insert(case_key, output_path.clone());
        }

        let mut source_path = repo_root.to_path_buf();
        for component in input_path.split('/') {
            source_path.push(component);
            let metadata = fs::symlink_metadata(&source_path).wrap_err_with(|| {
                format!("cannot inspect explicit source '{}'", source_path.display())
            })?;
            ensure!(
                !metadata.file_type().is_symlink(),
                "symlink is not permitted in explicit source '{}'",
                source_path.display()
            );
        }
        let resolved = fs::canonicalize(&source_path).wrap_err_with(|| {
            format!("cannot resolve explicit source '{}'", source_path.display())
        })?;
        ensure!(
            resolved.starts_with(&canonical_root),
            "explicit source '{}' escapes repository root '{}'",
            source_path.display(),
            repo_root.display()
        );
        ensure!(
            fs::metadata(&source_path)?.is_file(),
            "explicit source '{}' must be a regular file",
            source_path.display()
        );
        let source_bytes = fs::read(&source_path)
            .wrap_err_with(|| format!("cannot read explicit source '{}'", source_path.display()))?;
        let mut artifact = ProjectedArtifact {
            source_path: input_path.clone(),
            output_bytes: source_bytes.clone(),
            source_bytes,
            overlay: Some("feature".to_owned()),
        };
        render_java_artifact(output_path, &mut artifact, context)?;
        pending.insert(output_path.clone(), artifact);
    }
    let output_paths: BTreeSet<_> = artifacts.keys().chain(pending.keys()).cloned().collect();
    validate_no_output_collisions(&output_paths)?;
    artifacts.extend(pending);
    Ok(())
}

fn validate_no_output_collisions(output_paths: &BTreeSet<String>) -> Result<()> {
    for output_path in output_paths {
        let mut prefix = String::new();
        for component in output_path
            .split('/')
            .take(output_path.matches('/').count())
        {
            if !prefix.is_empty() {
                prefix.push('/');
            }
            prefix.push_str(component);
            ensure!(
                !output_paths.contains(&prefix),
                "projected file '{prefix}' conflicts with descendant '{output_path}'"
            );
        }
    }
    Ok(())
}

pub(crate) fn render_java_artifact(
    output_path: &str,
    artifact: &mut ProjectedArtifact,
    context: &ProjectionContext,
) -> Result<()> {
    if !Path::new(output_path)
        .extension()
        .is_some_and(|extension| extension.eq_ignore_ascii_case("java"))
    {
        return Ok(());
    }
    let (bom, java_bytes) = if artifact.source_bytes.starts_with(UTF8_BOM) {
        (UTF8_BOM, &artifact.source_bytes[UTF8_BOM.len()..])
    } else {
        (&[][..], artifact.source_bytes.as_slice())
    };
    let source = std::str::from_utf8(java_bytes)
        .wrap_err_with(|| format!("Java source '{output_path}' is not UTF-8"))?;
    let rendered = render_java_source(source, context)
        .wrap_err_with(|| format!("cannot project Java source '{output_path}'"))?;
    let line_ending = preferred_line_ending(source);
    artifact.output_bytes =
        Vec::with_capacity(bom.len() + GENERATED_BANNER.len() + line_ending.len() + rendered.len());
    artifact.output_bytes.extend_from_slice(bom);
    artifact
        .output_bytes
        .extend_from_slice(GENERATED_BANNER.as_bytes());
    artifact
        .output_bytes
        .extend_from_slice(line_ending.as_bytes());
    artifact.output_bytes.extend_from_slice(rendered.as_bytes());
    Ok(())
}

fn preferred_line_ending(source: &str) -> &'static str {
    if let Some(index) = source.find('\n') {
        if index
            .checked_sub(1)
            .and_then(|previous| source.as_bytes().get(previous))
            == Some(&b'\r')
        {
            "\r\n"
        } else {
            "\n"
        }
    } else if source.contains('\r') {
        "\r"
    } else {
        "\n"
    }
}

fn collect_root(
    source_root: &Path,
    overlay: Option<&String>,
    excluded: &BTreeSet<String>,
    allowed_output_paths: Option<&BTreeSet<String>>,
    canonical_case: &mut BTreeMap<String, String>,
    artifacts: &mut BTreeMap<String, ProjectedArtifact>,
) -> Result<()> {
    let metadata = fs::symlink_metadata(source_root)
        .wrap_err_with(|| format!("cannot inspect source root '{}'", source_root.display()))?;
    ensure!(
        !metadata.file_type().is_symlink() && metadata.is_dir(),
        "source root '{}' must be a real directory, not a symlink or file",
        source_root.display()
    );
    let canonical_root = fs::canonicalize(source_root)
        .wrap_err_with(|| format!("cannot resolve source root '{}'", source_root.display()))?;

    for entry in WalkDir::new(source_root)
        .follow_links(false)
        .sort_by_file_name()
    {
        let entry = entry.wrap_err_with(|| {
            format!("cannot enumerate source root '{}'", source_root.display())
        })?;
        if entry.path() == source_root {
            continue;
        }
        ensure!(
            !entry.file_type().is_symlink(),
            "symlink is not permitted in source projection: '{}'",
            entry.path().display()
        );
        let resolved = fs::canonicalize(entry.path())
            .wrap_err_with(|| format!("cannot resolve input '{}'", entry.path().display()))?;
        ensure!(
            resolved.starts_with(&canonical_root),
            "source path '{}' escapes root '{}'",
            entry.path().display(),
            source_root.display()
        );
        if entry.file_type().is_dir() {
            continue;
        }
        ensure!(
            entry.file_type().is_file(),
            "unsupported source entry '{}': expected a regular file",
            entry.path().display()
        );

        let relative = entry
            .path()
            .strip_prefix(source_root)
            .wrap_err("source walker returned a path outside its root")?;
        let relative = portable_relative_path(relative)?;
        if excluded.contains(&relative.to_ascii_lowercase()) {
            continue;
        }
        let output_path = format!("src/{relative}");
        if allowed_output_paths.is_some_and(|allowed| !allowed.contains(&output_path)) {
            continue;
        }
        let case_key = output_path.to_ascii_lowercase();
        if let Some(existing) = canonical_case.get(&case_key) {
            ensure!(
                existing == &output_path,
                "case-colliding projected paths '{existing}' and '{output_path}'"
            );
        } else {
            canonical_case.insert(case_key, output_path.clone());
        }

        let source_bytes = fs::read(entry.path())
            .wrap_err_with(|| format!("cannot read source '{}'", entry.path().display()))?;
        artifacts.insert(
            output_path.clone(),
            ProjectedArtifact {
                source_path: output_path,
                output_bytes: source_bytes.clone(),
                source_bytes,
                overlay: overlay.cloned(),
            },
        );
    }
    Ok(())
}

fn normalize_exclusions(excludes: &BTreeSet<String>) -> Result<BTreeSet<String>> {
    excludes
        .iter()
        .map(|exclude| {
            let relative = exclude.strip_prefix("src/").ok_or_else(|| {
                eyre::eyre!("excluded path '{exclude}' must be a canonical src/... output path")
            })?;
            validate_portable_path(relative)?;
            Ok(relative.to_ascii_lowercase())
        })
        .collect()
}

fn portable_relative_path(path: &Path) -> Result<String> {
    let mut components = Vec::new();
    for component in path.components() {
        let Component::Normal(name) = component else {
            bail!("source path '{}' is not relative", path.display());
        };
        let name = name
            .to_str()
            .ok_or_else(|| eyre::eyre!("source path '{}' is not UTF-8", path.display()))?;
        components.push(name);
    }
    let normalized = components.join("/");
    validate_portable_path(&normalized)?;
    Ok(normalized)
}

fn validate_portable_path(path: &str) -> Result<()> {
    ensure!(!path.is_empty(), "source path must not be empty");
    ensure!(
        !path
            .chars()
            .any(|character| character.is_control() || "\\<>:\"|?*".contains(character)),
        "source path '{path}' is not portable"
    );
    for part in path.split('/') {
        ensure!(
            !part.is_empty()
                && part != "."
                && part != ".."
                && !part.ends_with('.')
                && !part.ends_with(' ')
                && !is_windows_device_name(part),
            "source path '{path}' is not portable"
        );
    }
    Ok(())
}

fn is_windows_device_name(part: &str) -> bool {
    let stem = part.split('.').next().unwrap_or_default();
    let upper = stem.to_ascii_uppercase();
    matches!(upper.as_str(), "CON" | "PRN" | "AUX" | "NUL")
        || (upper.len() == 4
            && (upper.starts_with("COM") || upper.starts_with("LPT"))
            && matches!(upper.as_bytes()[3], b'1'..=b'9'))
}

fn validate_overlay_name(name: &str) -> Result<()> {
    ensure!(
        !name.is_empty()
            && name.as_bytes()[0].is_ascii_alphanumeric()
            && name.bytes().all(|byte| {
                byte.is_ascii_lowercase() || byte.is_ascii_digit() || b"._-".contains(&byte)
            }),
        "overlay name '{name}' must be a lowercase portable ID"
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn context() -> ProjectionContext {
        ProjectionContext {
            minecraft_version: "1.19.2".to_owned(),
            preset: "released-4.34.0".to_owned(),
            environment: "release".to_owned(),
            projection_key: "sfm-4.34.0/mc-1.19.2".to_owned(),
            features: BTreeMap::from([("touch_display".to_owned(), true)]),
            targets: BTreeMap::from([("mc_1_19_2".to_owned(), true)]),
        }
    }

    #[test]
    fn java_identity_and_conditional_render_without_touching_binary_bytes() {
        let root = tempfile::tempdir().unwrap();
        fs::create_dir_all(root.path().join("main/java")).unwrap();
        fs::create_dir_all(root.path().join("main/resources")).unwrap();
        fs::write(
            root.path().join("main/java/Plain.java"),
            b"class Plain {}\r\n",
        )
        .unwrap();
        fs::write(
            root.path().join("main/java/Feature.java"),
            b"{% if features.touch_display %}\nclass Feature {}\n{% endif %}\n",
        )
        .unwrap();
        fs::write(
            root.path().join("main/resources/bytes.dat"),
            [0_u8, 255, 128],
        )
        .unwrap();

        let artifacts =
            collect_projected_inputs(root.path(), &[], &context(), &BTreeSet::new()).unwrap();
        assert_eq!(
            artifacts["src/main/java/Plain.java"].output_bytes,
            format!("{GENERATED_BANNER}\r\nclass Plain {{}}\r\n").into_bytes()
        );
        assert_eq!(
            artifacts["src/main/java/Feature.java"].output_bytes,
            format!("{GENERATED_BANNER}\nclass Feature {{}}\n").into_bytes()
        );
        assert_eq!(
            artifacts["src/main/resources/bytes.dat"].output_bytes,
            [0_u8, 255, 128]
        );
        assert_eq!(
            artifacts["src/main/java/Plain.java"].source_path,
            "src/main/java/Plain.java"
        );
    }

    #[test]
    fn later_overlay_replaces_exact_output_path_and_records_its_name() {
        let primary = tempfile::tempdir().unwrap();
        let first = tempfile::tempdir().unwrap();
        let second = tempfile::tempdir().unwrap();
        for (root, bytes) in [
            (primary.path(), b"class Primary {}\n".as_slice()),
            (first.path(), b"class First {}\n".as_slice()),
            (second.path(), b"class Second {}\n".as_slice()),
        ] {
            fs::create_dir_all(root.join("main/java")).unwrap();
            fs::write(root.join("main/java/Example.java"), bytes).unwrap();
        }
        let overlays = [
            ("first".to_owned(), first.path().to_path_buf()),
            ("second".to_owned(), second.path().to_path_buf()),
        ];
        let artifacts =
            collect_projected_inputs(primary.path(), &overlays, &context(), &BTreeSet::new())
                .unwrap();
        assert_eq!(artifacts.len(), 1);
        assert_eq!(
            artifacts["src/main/java/Example.java"].output_bytes,
            format!("{GENERATED_BANNER}\nclass Second {{}}\n").into_bytes()
        );
        assert_eq!(
            artifacts["src/main/java/Example.java"].overlay.as_deref(),
            Some("second")
        );
    }

    #[test]
    fn replaced_primary_is_not_rendered_for_the_target() {
        let primary = tempfile::tempdir().unwrap();
        let overlay = tempfile::tempdir().unwrap();
        fs::write(
            primary.path().join("Example.java"),
            b"{% if features.not_registered %}\nclass Wrong {}\n{% endif %}\n",
        )
        .unwrap();
        fs::write(overlay.path().join("Example.java"), b"class Right {}\n").unwrap();

        let artifacts = collect_projected_inputs(
            primary.path(),
            &[("version".to_owned(), overlay.path().to_path_buf())],
            &context(),
            &BTreeSet::new(),
        )
        .unwrap();
        assert_eq!(
            artifacts["src/Example.java"].output_bytes,
            format!("{GENERATED_BANNER}\nclass Right {{}}\n").into_bytes()
        );
    }

    #[test]
    fn java_banner_follows_bom_and_uses_source_line_endings() {
        let root = tempfile::tempdir().unwrap();
        fs::write(
            root.path().join("Bom.java"),
            b"\xEF\xBB\xBFclass Bom {}\r\n",
        )
        .unwrap();
        let artifacts =
            collect_projected_inputs(root.path(), &[], &context(), &BTreeSet::new()).unwrap();
        let output = &artifacts["src/Bom.java"].output_bytes;
        let mut expected = UTF8_BOM.to_vec();
        expected.extend_from_slice(GENERATED_BANNER.as_bytes());
        expected.extend_from_slice(b"\r\nclass Bom {}\r\n");
        assert_eq!(output, &expected);
    }

    #[test]
    fn java_extension_is_compared_case_insensitively() {
        let root = tempfile::tempdir().unwrap();
        fs::write(root.path().join("Upper.JAVA"), b"class Upper {}\n").unwrap();
        let artifacts =
            collect_projected_inputs(root.path(), &[], &context(), &BTreeSet::new()).unwrap();
        assert_eq!(
            artifacts["src/Upper.JAVA"].output_bytes,
            format!("{GENERATED_BANNER}\nclass Upper {{}}\n").into_bytes()
        );
    }

    #[test]
    fn explicit_feature_input_overrides_shared_source() {
        let repo = tempfile::tempdir().unwrap();
        let primary = repo.path().join("src");
        let feature = repo.path().join("feature");
        fs::create_dir_all(&primary).unwrap();
        fs::create_dir_all(&feature).unwrap();
        fs::write(primary.join("Example.java"), b"class Shared {}\n").unwrap();
        fs::write(feature.join("Example.java"), b"class Feature {}\n").unwrap();
        let mut artifacts =
            collect_projected_inputs(&primary, &[], &context(), &BTreeSet::new()).unwrap();

        apply_explicit_inputs(
            repo.path(),
            &mut artifacts,
            &BTreeMap::from([(
                "src/Example.java".to_owned(),
                "feature/Example.java".to_owned(),
            )]),
            &context(),
        )
        .unwrap();

        let output = &artifacts["src/Example.java"];
        assert_eq!(
            output.output_bytes,
            format!("{GENERATED_BANNER}\nclass Feature {{}}\n").into_bytes()
        );
        assert_eq!(output.source_path, "feature/Example.java");
        assert_eq!(output.overlay.as_deref(), Some("feature"));
    }

    #[test]
    fn explicit_input_rejects_escape_without_mutating_selected_artifacts() {
        let repo = tempfile::tempdir().unwrap();
        let primary = repo.path().join("src");
        fs::create_dir_all(&primary).unwrap();
        fs::write(primary.join("Example.java"), b"class Shared {}\n").unwrap();
        let mut artifacts =
            collect_projected_inputs(&primary, &[], &context(), &BTreeSet::new()).unwrap();
        let previous = artifacts["src/Example.java"].output_bytes.clone();

        let error = apply_explicit_inputs(
            repo.path(),
            &mut artifacts,
            &BTreeMap::from([("src/Example.java".to_owned(), "../outside.java".to_owned())]),
            &context(),
        )
        .unwrap_err();
        assert!(format!("{error:?}").contains("not portable"));
        assert_eq!(artifacts["src/Example.java"].output_bytes, previous);
    }

    #[cfg(unix)]
    #[test]
    fn explicit_input_rejects_symlink_in_parent_path() {
        let repo = tempfile::tempdir().unwrap();
        let real = repo.path().join("real");
        fs::create_dir_all(&real).unwrap();
        fs::write(real.join("Example.java"), b"class Example {}\n").unwrap();
        std::os::unix::fs::symlink(&real, repo.path().join("linked")).unwrap();
        let mut artifacts = BTreeMap::new();
        let error = apply_explicit_inputs(
            repo.path(),
            &mut artifacts,
            &BTreeMap::from([(
                "src/Example.java".to_owned(),
                "linked/Example.java".to_owned(),
            )]),
            &context(),
        )
        .unwrap_err();
        assert!(format!("{error:?}").contains("symlink"));
        assert!(artifacts.is_empty());
    }

    #[cfg(windows)]
    #[test]
    fn explicit_input_rejects_symlink_when_windows_can_create_it() {
        let repo = tempfile::tempdir().unwrap();
        let real = repo.path().join("real");
        fs::create_dir_all(&real).unwrap();
        fs::write(real.join("Example.java"), b"class Example {}\n").unwrap();
        if std::os::windows::fs::symlink_dir(&real, repo.path().join("linked")).is_err() {
            return;
        }
        let mut artifacts = BTreeMap::new();
        let error = apply_explicit_inputs(
            repo.path(),
            &mut artifacts,
            &BTreeMap::from([(
                "src/Example.java".to_owned(),
                "linked/Example.java".to_owned(),
            )]),
            &context(),
        )
        .unwrap_err();
        assert!(format!("{error:?}").contains("symlink"));
        assert!(artifacts.is_empty());
    }

    #[test]
    fn excluded_file_is_absent_even_when_an_overlay_defines_it() {
        let primary = tempfile::tempdir().unwrap();
        let overlay = tempfile::tempdir().unwrap();
        for root in [primary.path(), overlay.path()] {
            fs::create_dir_all(root.join("main/java")).unwrap();
            fs::write(root.join("main/java/Disabled.java"), b"class Disabled {}\n").unwrap();
        }
        let excludes = BTreeSet::from(["src/main/java/Disabled.java".to_owned()]);
        let artifacts = collect_projected_inputs(
            primary.path(),
            &[("version".to_owned(), overlay.path().to_path_buf())],
            &context(),
            &excludes,
        )
        .unwrap();
        assert!(artifacts.is_empty());
    }

    #[test]
    fn release_allowlist_masks_invalid_development_java_before_rendering() {
        let root = tempfile::tempdir().unwrap();
        fs::write(root.path().join("Released.java"), b"class Released {}\n").unwrap();
        fs::write(
            root.path().join("Development.java"),
            b"{% if features.not_registered %}\nclass Development {}\n{% endif %}\n",
        )
        .unwrap();
        let allowed = BTreeSet::from(["src/Released.java".to_owned()]);
        let artifacts = collect_projected_inputs_with_allowlist(
            root.path(),
            &[],
            &context(),
            &BTreeSet::new(),
            Some(&allowed),
        )
        .unwrap();
        assert_eq!(artifacts.len(), 1);
        assert!(artifacts.contains_key("src/Released.java"));
    }

    #[test]
    fn rejects_case_collisions_and_file_directory_conflicts() {
        let primary = tempfile::tempdir().unwrap();
        let overlay = tempfile::tempdir().unwrap();
        fs::create_dir_all(primary.path().join("main/java")).unwrap();
        fs::create_dir_all(overlay.path().join("main/java")).unwrap();
        fs::write(primary.path().join("main/java/Thing.java"), b"primary").unwrap();
        fs::write(overlay.path().join("main/java/thing.java"), b"overlay").unwrap();
        let error = collect_projected_inputs(
            primary.path(),
            &[("version".to_owned(), overlay.path().to_path_buf())],
            &context(),
            &BTreeSet::new(),
        )
        .unwrap_err();
        assert!(format!("{error:?}").contains("case-colliding"));

        let first = tempfile::tempdir().unwrap();
        let second = tempfile::tempdir().unwrap();
        fs::write(first.path().join("a"), b"file").unwrap();
        fs::create_dir_all(second.path().join("a")).unwrap();
        fs::write(second.path().join("a/b"), b"nested").unwrap();
        let error = collect_projected_inputs(
            first.path(),
            &[("version".to_owned(), second.path().to_path_buf())],
            &context(),
            &BTreeSet::new(),
        )
        .unwrap_err();
        assert!(format!("{error:?}").contains("conflicts with descendant"));
    }

    #[cfg(unix)]
    #[test]
    fn rejects_symlinked_input() {
        let root = tempfile::tempdir().unwrap();
        std::os::unix::fs::symlink("outside", root.path().join("link.java")).unwrap();
        let error =
            collect_projected_inputs(root.path(), &[], &context(), &BTreeSet::new()).unwrap_err();
        assert!(format!("{error:?}").contains("symlink"));
    }

    #[cfg(windows)]
    #[test]
    fn rejects_symlinked_input_when_windows_can_create_it() {
        let root = tempfile::tempdir().unwrap();
        let target = root.path().join("target.java");
        fs::write(&target, b"class Target {}").unwrap();
        let link = root.path().join("link.java");
        if std::os::windows::fs::symlink_file(&target, &link).is_err() {
            // Developer mode or SeCreateSymbolicLinkPrivilege is unavailable.
            return;
        }
        let error =
            collect_projected_inputs(root.path(), &[], &context(), &BTreeSet::new()).unwrap_err();
        assert!(format!("{error:?}").contains("symlink"));
    }
}
