//! Pure fresh-producer output sealing, not filesystem or process authority.
//!
//! A host must obtain observations from a freshly owned invocation/engine and
//! reject reparse points before calling this module. An observation is not an
//! OS attestation. This module batch-preflights observations, copies the supplied
//! bytes into immutable memory, rehashes the copies and preserves consumer order.
//! No caller can turn its receipt into a native execution permit.

use super::promotion::validate_relative_path;
use super::provenance::sha256;
use eyre::Result;
use eyre::ensure;
use facet::Facet;
use std::collections::BTreeMap;
use std::collections::BTreeSet;
use std::sync::Arc;

const MAX_OUTPUTS: usize = 256;
const MAX_OUTPUT_BYTES: usize = 512 * 1024 * 1024;
const MAX_BATCH_BYTES: usize = 1024 * 1024 * 1024;

/// Portable exact context, independent of machine paths and branch aliases.
#[derive(Clone, Debug, Eq, Facet, PartialEq)]
pub struct NfrtProducerScope {
    pub invocation_id: String,
    pub prepared_contract_sha256: String,
    pub project_preparation_sha256: String,
    pub source_lock_sha256: String,
    pub recipe_id: String,
    pub graph_plan_sha256: String,
    pub tool_sdk_sha256: String,
}

/// A declared producer/output pair in an already authenticated graph plan.
#[derive(Clone, Debug, Eq, Facet, PartialEq)]
pub struct NfrtProducerDeclaration {
    pub producer_id: String,
    pub output_id: String,
    pub output_type: String,
    pub output_relative_path: String,
    pub producer_inputs_sha256: String,
    pub tool_classpath_and_arguments_sha256: String,
}

/// Host observations remain untrusted data until checked against declarations.
#[derive(Clone, Debug, Eq, PartialEq)]
#[expect(
    clippy::struct_excessive_bools,
    reason = "Independent producer observations must each be validated; they are not lifecycle alternatives."
)]
pub struct NfrtProducerObservation {
    pub scope: NfrtProducerScope,
    pub declaration: NfrtProducerDeclaration,
    pub belongs_to_fresh_engine: bool,
    pub completed: bool,
    pub restored_from_cache: bool,
    pub regular_file: bool,
    pub reparse_free_ancestry: bool,
    pub before_file_identity: String,
    pub after_file_identity: String,
    pub before_bytes: usize,
    pub after_bytes: usize,
}

/// Bytes and post-read identity from the later separately reviewed host.
/// The pure model cannot attest that these came from an OS handle.
#[derive(Debug)]
pub struct NfrtProducerRead {
    pub bytes: Vec<u8>,
    pub after_file_identity: String,
    pub after_bytes: usize,
    pub reparse_free_ancestry: bool,
}

/// Transfer identity for generated bytes, never an accepted dependency pin.
#[derive(Clone, Debug, Eq, Facet, PartialEq)]
#[expect(
    clippy::struct_excessive_bools,
    reason = "Serialized independent evidence claims preserve distinct authority boundaries."
)]
pub struct NfrtProducerOutputReceipt {
    pub schema: String,
    pub scope: NfrtProducerScope,
    pub declaration: NfrtProducerDeclaration,
    pub snapshot_relative_path: String,
    pub bytes: usize,
    pub full_sha256: String,
    pub completion_was_fresh: bool,
    pub inherited_cache_restore_disabled: bool,
    pub memory_snapshot_immutable: bool,
    pub os_filesystem_attested: bool,
    pub native_execution_enabled: bool,
}

/// Private declaration set: indexes are lookup aids, not sorted execution rows.
#[derive(Clone, Debug)]
pub struct NfrtProducerPlan {
    scope: NfrtProducerScope,
    declarations: Vec<NfrtProducerDeclaration>,
}

#[derive(Clone, Debug)]
pub struct SealedNfrtProducerOutput {
    receipt: NfrtProducerOutputReceipt,
    bytes: Arc<[u8]>,
}

impl SealedNfrtProducerOutput {
    #[must_use]
    pub fn receipt(&self) -> &NfrtProducerOutputReceipt {
        &self.receipt
    }

    #[must_use]
    pub fn bytes(&self) -> &[u8] {
        &self.bytes
    }

    /// Rehash the immutable transfer before a later host writes its snapshot.
    ///
    /// # Errors
    /// Rejects any changed receipt/byte relationship. This performs no I/O.
    pub fn recheck(&self) -> Result<()> {
        ensure!(
            self.bytes.len() == self.receipt.bytes
                && sha256(&self.bytes) == self.receipt.full_sha256,
            "fresh producer memory snapshot changed"
        );
        Ok(())
    }
}

impl NfrtProducerPlan {
    /// Bind only an explicit host-reviewed graph, without inventing producers.
    ///
    /// # Errors
    /// Rejects unsafe/duplicate output identities, paths and context digests.
    /// Host graph/ownership proof is separate from this pure model validation.
    pub fn from_declared_graph(
        scope: NfrtProducerScope,
        declarations: Vec<NfrtProducerDeclaration>,
    ) -> Result<Self> {
        validate_scope(&scope)?;
        ensure!(
            !declarations.is_empty() && declarations.len() <= MAX_OUTPUTS,
            "fresh producer graph declaration count is unavailable or oversized"
        );
        let mut ids = BTreeSet::new();
        let mut paths = BTreeSet::new();
        for declaration in &declarations {
            validate_declaration(declaration)?;
            ensure!(
                ids.insert((
                    declaration.producer_id.clone(),
                    declaration.output_id.clone()
                )) && paths.insert(declaration.output_relative_path.to_ascii_lowercase()),
                "duplicate producer/output or case-alias path"
            );
        }
        Ok(Self {
            scope,
            declarations,
        })
    }

    /// Batch-preflight every consumer before invoking any byte-read callback.
    ///
    /// The callback supplies bytes read by a future separately reviewed host.
    /// Successful observations cannot attest actual Windows handle/ACL safety.
    /// Only one immutable copy is made per producer; repeated consumers retain
    /// their original order and share that same private snapshot.
    ///
    /// # Errors
    /// Rejects foreign/unknown/noncompleted/cached/unsafe/changed observations
    /// before reads; rejects a wrong byte length or oversized complete batch.
    pub fn seal_classpath_batch<F>(
        &self,
        observations: &[NfrtProducerObservation],
        mut read: F,
    ) -> Result<Vec<SealedNfrtProducerOutput>>
    where
        F: FnMut(&NfrtProducerDeclaration) -> Result<NfrtProducerRead>,
    {
        ensure!(
            observations.len() <= MAX_OUTPUTS,
            "fresh producer classpath batch exceeds its bounded count"
        );
        let mut unique = BTreeMap::<usize, &NfrtProducerObservation>::new();
        let mut order = Vec::with_capacity(observations.len());
        let mut total = 0usize;
        for observation in observations {
            let slot = self.validate_observation(observation)?;
            if let Some(previous) = unique.get(&slot) {
                ensure!(
                    *previous == observation,
                    "repeated producer consumer changed observation"
                );
            } else {
                total = total
                    .checked_add(observation.before_bytes)
                    .ok_or_else(|| eyre::eyre!("producer batch length overflow"))?;
                ensure!(
                    total <= MAX_BATCH_BYTES,
                    "producer batch exceeds bounded bytes"
                );
                unique.insert(slot, observation);
            }
            order.push(slot);
        }
        let mut copies = BTreeMap::new();
        // First-consumer order, not BTree index order, controls callback reads.
        for slot in &order {
            if copies.contains_key(slot) {
                continue;
            }
            let observation = unique[slot];
            let result = read(&observation.declaration)?;
            ensure!(
                result.bytes.len() == observation.before_bytes
                    && result.after_bytes == observation.before_bytes
                    && result.after_file_identity == observation.before_file_identity
                    && result.reparse_free_ancestry,
                "producer source read identity/length/ancestry changed during payload read"
            );
            let raw = result.bytes;
            let full_sha256 = sha256(&raw);
            let bytes: Arc<[u8]> = Arc::from(raw.into_boxed_slice());
            ensure!(
                sha256(&bytes) == full_sha256,
                "immutable producer copy changed"
            );
            let receipt = NfrtProducerOutputReceipt {
                schema: "sfm:nfrt_fresh_producer_output@1".to_owned(),
                scope: self.scope.clone(),
                declaration: observation.declaration.clone(),
                snapshot_relative_path: format!("inputs/generated/{slot:04}.bin"),
                bytes: bytes.len(),
                full_sha256,
                completion_was_fresh: true,
                inherited_cache_restore_disabled: true,
                memory_snapshot_immutable: true,
                os_filesystem_attested: false,
                native_execution_enabled: false,
            };
            copies.insert(*slot, SealedNfrtProducerOutput { receipt, bytes });
        }
        order
            .into_iter()
            .map(|slot| {
                copies
                    .get(&slot)
                    .cloned()
                    .ok_or_else(|| eyre::eyre!("producer snapshot missing"))
            })
            .collect()
    }

    fn validate_observation(&self, observation: &NfrtProducerObservation) -> Result<usize> {
        ensure!(
            observation.scope == self.scope,
            "producer scope is foreign or changed"
        );
        let slot = self
            .declarations
            .iter()
            .position(|value| value == &observation.declaration)
            .ok_or_else(|| eyre::eyre!("producer/output is not declared by exact graph"))?;
        ensure!(
            observation.belongs_to_fresh_engine
                && observation.completed
                && !observation.restored_from_cache
                && observation.regular_file
                && observation.reparse_free_ancestry,
            "producer is foreign, noncompleted, cached or outside the safe regular-file boundary"
        );
        ensure!(
            !observation.before_file_identity.is_empty()
                && observation.before_file_identity.len() <= 4096
                && observation.before_file_identity == observation.after_file_identity
                && observation.before_bytes == observation.after_bytes
                && observation.before_bytes > 0
                && observation.before_bytes <= MAX_OUTPUT_BYTES,
            "producer source read identity/length changed or is oversized"
        );
        Ok(slot)
    }
}

fn validate_scope(scope: &NfrtProducerScope) -> Result<()> {
    safe_token(&scope.invocation_id)?;
    ensure!(
        scope.recipe_id.len() <= 512 && !scope.recipe_id.is_empty(),
        "producer recipe missing"
    );
    for digest in [
        &scope.prepared_contract_sha256,
        &scope.project_preparation_sha256,
        &scope.source_lock_sha256,
        &scope.graph_plan_sha256,
        &scope.tool_sdk_sha256,
    ] {
        validate_digest(digest)?;
    }
    Ok(())
}

fn validate_declaration(declaration: &NfrtProducerDeclaration) -> Result<()> {
    for token in [
        &declaration.producer_id,
        &declaration.output_id,
        &declaration.output_type,
    ] {
        safe_token(token)?;
    }
    validate_relative_path(&declaration.output_relative_path)?;
    ensure!(
        declaration.output_relative_path.starts_with("work/")
            && declaration.output_relative_path.len() <= 4096,
        "producer output is outside the fresh invocation work root"
    );
    validate_digest(&declaration.producer_inputs_sha256)?;
    validate_digest(&declaration.tool_classpath_and_arguments_sha256)
}

fn safe_token(token: &str) -> Result<()> {
    ensure!(
        !token.is_empty()
            && token.len() <= 128
            && token
                .bytes()
                .all(|value| value.is_ascii_alphanumeric() || matches!(value, b'-' | b'_' | b'.')),
        "unsafe producer identity token"
    );
    Ok(())
}

fn validate_digest(digest: &str) -> Result<()> {
    let value = digest.strip_prefix("sha256:").unwrap_or("");
    ensure!(
        value.len() == 64
            && value
                .bytes()
                .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte)),
        "producer identity is not full lowercase SHA-256"
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::cell::Cell;

    fn scope() -> NfrtProducerScope {
        NfrtProducerScope {
            invocation_id: "fresh-fixture".to_owned(),
            prepared_contract_sha256: sha256(b"contract"),
            project_preparation_sha256: sha256(b"project"),
            source_lock_sha256: sha256(b"lock"),
            recipe_id: "sfm:recipe@1".to_owned(),
            graph_plan_sha256: sha256(b"graph"),
            tool_sdk_sha256: sha256(b"sdk"),
        }
    }

    fn declaration(id: &str) -> NfrtProducerDeclaration {
        NfrtProducerDeclaration {
            producer_id: id.to_owned(),
            output_id: "jar".to_owned(),
            output_type: "jar".to_owned(),
            output_relative_path: format!("work/{id}/result.jar"),
            producer_inputs_sha256: sha256(b"inputs"),
            tool_classpath_and_arguments_sha256: sha256(b"args"),
        }
    }

    fn observed(id: &str) -> NfrtProducerObservation {
        NfrtProducerObservation {
            scope: scope(),
            declaration: declaration(id),
            belongs_to_fresh_engine: true,
            completed: true,
            restored_from_cache: false,
            regular_file: true,
            reparse_free_ancestry: true,
            before_file_identity: "stable-file-key".to_owned(),
            after_file_identity: "stable-file-key".to_owned(),
            before_bytes: 3,
            after_bytes: 3,
        }
    }

    fn read_result(raw: &[u8]) -> NfrtProducerRead {
        NfrtProducerRead {
            bytes: raw.to_vec(),
            after_file_identity: "stable-file-key".to_owned(),
            after_bytes: raw.len(),
            reparse_free_ancestry: true,
        }
    }

    #[test]
    fn batch_refusal_has_zero_read_callbacks() -> Result<()> {
        let plan = NfrtProducerPlan::from_declared_graph(scope(), vec![declaration("a")])?;
        for change in 0..10 {
            let mut bad = observed("a");
            match change {
                0 => bad.scope.invocation_id = "foreign".to_owned(),
                1 => bad.declaration.output_id = "unknown".to_owned(),
                2 => bad.belongs_to_fresh_engine = false,
                3 => bad.completed = false,
                4 => bad.restored_from_cache = true,
                5 => bad.regular_file = false,
                6 => bad.reparse_free_ancestry = false,
                7 => bad.after_file_identity = "changed".to_owned(),
                8 => bad.after_bytes = 4,
                _ => {
                    bad.before_bytes = MAX_OUTPUT_BYTES + 1;
                    bad.after_bytes = bad.before_bytes;
                }
            }
            let reads = Cell::new(0);
            let result = plan.seal_classpath_batch(&[observed("a"), bad], |_| {
                reads.set(reads.get() + 1);
                Ok(read_result(b"abc"))
            });
            ensure!(
                result.is_err() && reads.get() == 0,
                "refused batch read bytes"
            );
        }
        Ok(())
    }

    #[test]
    fn copies_once_preserves_order_duplicates_and_cannot_enable_native() -> Result<()> {
        let plan = NfrtProducerPlan::from_declared_graph(
            scope(),
            vec![declaration("a"), declaration("b")],
        )?;
        let mut reads = Vec::new();
        let outputs =
            plan.seal_classpath_batch(&[observed("b"), observed("a"), observed("b")], |value| {
                reads.push(value.producer_id.clone());
                Ok(read_result(b"abc"))
            })?;
        ensure!(
            reads == ["b", "a"]
                && outputs
                    .iter()
                    .map(|value| value.receipt().declaration.producer_id.as_str())
                    .collect::<Vec<_>>()
                    == ["b", "a", "b"],
            "producer order changed"
        );
        ensure!(
            Arc::ptr_eq(&outputs[0].bytes, &outputs[2].bytes),
            "duplicate consumer copied again"
        );
        for output in outputs {
            output.recheck()?;
            ensure!(
                output.bytes() == b"abc"
                    && !output.receipt().native_execution_enabled
                    && !output.receipt().os_filesystem_attested,
                "memory receipt claimed OS/execution authority"
            );
        }
        Ok(())
    }

    #[test]
    fn declaration_and_byte_mismatches_fail_closed() -> Result<()> {
        for path in [
            "outside.jar",
            "work/../outside.jar",
            "work/A.jar",
            "work/a.jar",
        ] {
            let mut first = declaration("a");
            first.output_relative_path = path.to_owned();
            let mut second = declaration("b");
            second.output_relative_path = "work/a.jar".to_owned();
            ensure!(
                NfrtProducerPlan::from_declared_graph(scope(), vec![first, second]).is_err(),
                "unsafe or aliased declaration accepted"
            );
        }
        let plan = NfrtProducerPlan::from_declared_graph(scope(), vec![declaration("a")])?;
        ensure!(
            plan.seal_classpath_batch(&[observed("a")], |_| Ok(read_result(b"wrong")))
                .is_err(),
            "wrong read length accepted"
        );
        Ok(())
    }

    #[test]
    fn post_read_change_refuses_before_issuing_snapshot() -> Result<()> {
        let plan = NfrtProducerPlan::from_declared_graph(scope(), vec![declaration("a")])?;
        for change in 0..3 {
            let result = plan.seal_classpath_batch(&[observed("a")], |_| {
                let mut read = read_result(b"abc");
                match change {
                    0 => read.after_file_identity = "replaced".to_owned(),
                    1 => read.after_bytes = 4,
                    _ => read.reparse_free_ancestry = false,
                }
                Ok(read)
            });
            ensure!(
                result.is_err(),
                "post-read source change produced a receipt"
            );
        }
        Ok(())
    }
}
