//! Read-only parity check for the checked-in 4.34.0 release source projections.

use super::provenance::sha256;
use super::release_baseline::RELEASE_4_34_0_TAGS;
use super::release_baseline::ReleaseBaselineReport;
use std::fs;
use std::path::Path;

const UTF8_BOM: &[u8] = b"\xEF\xBB\xBF";
const GENERATED_BANNER: &[u8] =
    b"// GENERATED by sfm-propagate-changes; edit the primary source or reconcile this file.";
const EXPECTED_RELEASE_MEMBERS: [(&str, usize); 10] = [
    ("1.19.2", 995),
    ("1.19.4", 995),
    ("1.20", 995),
    ("1.20.1", 997),
    ("1.20.2", 997),
    ("1.20.3", 997),
    ("1.20.4", 997),
    ("1.21.0", 999),
    ("1.21.1", 1000),
    ("26.1.2", 1008),
];

#[test]
fn checked_in_release_sources_match_all_generated_counterparts() {
    let repository_root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(3)
        .expect("CLI crate must be three directories below the repository root");
    let mut mismatches = Vec::new();
    let mut total_members = 0;

    for ((target_id, expected_count), (pinned_id, release_tag, expected_commit)) in
        EXPECTED_RELEASE_MEMBERS
            .into_iter()
            .zip(RELEASE_4_34_0_TAGS)
    {
        assert_eq!(target_id, pinned_id, "release target list changed");
        let manifest_path =
            format!("platform/minecraft/release-baselines/{release_tag}/import.json");
        let manifest = fs::read_to_string(repository_root.join(&manifest_path))
            .unwrap_or_else(|error| panic!("{manifest_path}: {error}"));
        let report = ReleaseBaselineReport::from_json(&manifest)
            .unwrap_or_else(|error| panic!("{manifest_path}: {error}"));
        assert_eq!(report.targets.len(), 1, "{manifest_path}");
        let target = &report.targets[0];
        assert_eq!(target.target_id, target_id, "{manifest_path}");
        assert_eq!(target.release_tag, release_tag, "{manifest_path}");
        assert_eq!(target.tag_commit, expected_commit, "{manifest_path}");

        let mut target_members = 0;
        for (source_path, record) in &target.paths {
            let Some(expected_hash) = record.release_sha256.as_deref() else {
                continue;
            };
            target_members += 1;
            total_members += 1;

            let generated_path = format!("platform/minecraft/mc-version/{target_id}/{source_path}");
            if !is_safe_source_path(source_path) {
                mismatches.push(format!(
                    "{manifest_path}: unsafe release path '{source_path}'"
                ));
                continue;
            }
            let generated = match fs::read(repository_root.join(&generated_path)) {
                Ok(bytes) => bytes,
                Err(error) => {
                    mismatches.push(format!("{generated_path}: {error}"));
                    continue;
                }
            };
            let source_bytes = if Path::new(source_path)
                .extension()
                .is_some_and(|extension| extension.eq_ignore_ascii_case("java"))
            {
                match remove_generated_java_banner(&generated) {
                    Ok(bytes) => bytes,
                    Err(reason) => {
                        mismatches.push(format!("{generated_path}: {reason}"));
                        continue;
                    }
                }
            } else {
                generated
            };
            let actual_hash = sha256(&source_bytes);
            if actual_hash != expected_hash {
                mismatches.push(format!(
                    "{generated_path}: expected release source {expected_hash}, found {actual_hash}"
                ));
            }
        }
        if target_members != expected_count {
            mismatches.push(format!(
                "{manifest_path}: expected {expected_count} release members, found {target_members}"
            ));
        }
    }

    if total_members != 9_980 {
        mismatches.push(format!(
            "release manifest total: expected 9,980 members, found {total_members}"
        ));
    }
    assert!(
        mismatches.is_empty(),
        "release source parity mismatches:\n{}",
        mismatches.join("\n")
    );
}

fn is_safe_source_path(path: &str) -> bool {
    path.starts_with("src/")
        && !path.contains('\\')
        && path
            .split('/')
            .all(|component| !component.is_empty() && component != "." && component != "..")
}

fn remove_generated_java_banner(generated: &[u8]) -> Result<Vec<u8>, &'static str> {
    let (bom, after_bom) = if let Some(rest) = generated.strip_prefix(UTF8_BOM) {
        (UTF8_BOM, rest)
    } else {
        (&[][..], generated)
    };
    let after_banner = after_bom
        .strip_prefix(GENERATED_BANNER)
        .ok_or("missing exact generated Java banner")?;
    let (banner_line_ending, source) = if let Some(rest) = after_banner.strip_prefix(b"\r\n") {
        (&b"\r\n"[..], rest)
    } else if let Some(rest) = after_banner.strip_prefix(b"\n") {
        (&b"\n"[..], rest)
    } else if let Some(rest) = after_banner.strip_prefix(b"\r") {
        (&b"\r"[..], rest)
    } else {
        return Err("generated Java banner has no line ending");
    };
    if source.starts_with(UTF8_BOM) {
        return Err("Java BOM occurs after generated banner");
    }
    if banner_line_ending != preferred_line_ending(source) {
        return Err("generated Java banner uses a different line ending from the source");
    }

    let mut original = Vec::with_capacity(bom.len() + source.len());
    original.extend_from_slice(bom);
    original.extend_from_slice(source);
    Ok(original)
}

fn preferred_line_ending(source: &[u8]) -> &'static [u8] {
    if let Some(index) = source.iter().position(|byte| *byte == b'\n') {
        if index > 0 && source[index - 1] == b'\r' {
            b"\r\n"
        } else {
            b"\n"
        }
    } else if source.contains(&b'\r') {
        b"\r"
    } else {
        b"\n"
    }
}
