//! Read-only parity check for the checked-in 4.34.0 release source projections.

use super::provenance::sha256;
use super::release_baseline::BaselinePathRecord;
use super::release_baseline::RELEASE_4_34_0_TAGS;
use super::release_baseline::ReleaseBaselineReport;
use super::release_baseline::ReleaseBaselineTargetReport;
use super::release_baseline::frozen_git_command;
use eyre::Result;
use eyre::WrapErr;
use eyre::bail;
use eyre::ensure;
use std::collections::BTreeMap;
use std::fs;
use std::io::BufRead;
use std::io::BufReader;
use std::io::Read;
use std::io::Write;
use std::path::Path;
use std::process::Command;
use std::process::Stdio;

const UTF8_BOM: &[u8] = b"\xEF\xBB\xBF";
const GENERATED_BANNER: &[u8] =
    b"// GENERATED by sfm-propagate-changes; edit the primary source or reconcile this file.";
const MAX_SOURCE_BLOB_BYTES: usize = 128 * 1024 * 1024;
const EXPECTED_RELEASE_MEMBERS: [(&str, usize); 10] = [
    ("1.19.2", 995),
    ("1.19.4", 995),
    ("1.20", 995),
    ("1.20.1", 997),
    ("1.20.2", 997),
    ("1.20.3", 997),
    ("1.20.4", 997),
    ("1.21.0", 999),
    ("1.21.1", 1000),
    ("26.1.2", 1008),
];

#[test]
fn checked_in_release_sources_match_all_generated_counterparts() {
    let repository_root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(3)
        .expect("CLI crate must be three directories below the repository root");
    let mut mismatches = Vec::new();
    let mut total_members = 0;

    for ((target_id, expected_count), (pinned_id, release_tag, expected_commit)) in
        EXPECTED_RELEASE_MEMBERS
            .into_iter()
            .zip(RELEASE_4_34_0_TAGS)
    {
        assert_eq!(target_id, pinned_id, "release target list changed");
        let manifest_path =
            format!("platform/minecraft/release-baselines/{release_tag}/import.json");
        let manifest = fs::read_to_string(repository_root.join(&manifest_path))
            .unwrap_or_else(|error| panic!("{manifest_path}: {error}"));
        let report = ReleaseBaselineReport::from_json(&manifest)
            .unwrap_or_else(|error| panic!("{manifest_path}: {error}"));
        assert_eq!(report.targets.len(), 1, "{manifest_path}");
        let target = &report.targets[0];
        assert_eq!(target.target_id, target_id, "{manifest_path}");
        assert_eq!(target.release_tag, release_tag, "{manifest_path}");
        assert_eq!(target.tag_commit, expected_commit, "{manifest_path}");

        let mut target_members = 0;
        for (source_path, record) in &target.paths {
            let Some(expected_hash) = record.release_sha256.as_deref() else {
                continue;
            };
            target_members += 1;
            total_members += 1;

            let generated_path = format!("platform/minecraft/mc-version/{target_id}/{source_path}");
            if !is_safe_source_path(source_path) {
                mismatches.push(format!(
                    "{manifest_path}: unsafe release path '{source_path}'"
                ));
                continue;
            }
            let generated = match fs::read(repository_root.join(&generated_path)) {
                Ok(bytes) => bytes,
                Err(error) => {
                    mismatches.push(format!("{generated_path}: {error}"));
                    continue;
                }
            };
            let source_bytes = if Path::new(source_path)
                .extension()
                .is_some_and(|extension| extension.eq_ignore_ascii_case("java"))
            {
                match remove_generated_java_banner(&generated) {
                    Ok(bytes) => bytes,
                    Err(reason) => {
                        mismatches.push(format!("{generated_path}: {reason}"));
                        continue;
                    }
                }
            } else {
                generated
            };
            let actual_hash = sha256(&source_bytes);
            if actual_hash != expected_hash {
                mismatches.push(format!(
                    "{generated_path}: expected release source {expected_hash}, found {actual_hash}"
                ));
            }
        }
        if target_members != expected_count {
            mismatches.push(format!(
                "{manifest_path}: expected {expected_count} release members, found {target_members}"
            ));
        }
    }

    if total_members != 9_980 {
        mismatches.push(format!(
            "release manifest total: expected 9,980 members, found {total_members}"
        ));
    }
    assert!(
        mismatches.is_empty(),
        "release source parity mismatches:\n{}",
        mismatches.join("\n")
    );
}

#[test]
fn checked_in_release_sources_match_pinned_local_tag_blobs() -> Result<()> {
    let repository_root = fs::canonicalize(
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .ancestors()
            .nth(3)
            .expect("CLI crate must be three directories below the repository root"),
    )?;
    let mut total_members = 0;

    for ((target_id, expected_count), (pinned_id, release_tag, expected_commit)) in
        EXPECTED_RELEASE_MEMBERS
            .into_iter()
            .zip(RELEASE_4_34_0_TAGS)
    {
        ensure!(target_id == pinned_id, "release target list changed");
        let tag_ref = format!("refs/tags/{release_tag}^{{commit}}");
        let resolved = parity_git_stdout(&repository_root, &["rev-parse", "--verify", &tag_ref])?;
        ensure!(
            resolved == format!("{expected_commit}\n").as_bytes(),
            "local tag '{release_tag}' does not resolve to pinned commit {expected_commit}"
        );
        let manifest_path =
            format!("platform/minecraft/release-baselines/{release_tag}/import.json");
        let report = ReleaseBaselineReport::from_json(&fs::read_to_string(
            repository_root.join(&manifest_path),
        )?)?;
        ensure!(
            report.targets.len() == 1,
            "{manifest_path}: target count changed"
        );
        let target = &report.targets[0];
        ensure!(
            target.target_id == target_id
                && target.release_tag == release_tag
                && target.tag_commit == expected_commit,
            "{manifest_path}: pinned target identity changed"
        );

        let tree = parse_source_tree(&parity_git_stdout(
            &repository_root,
            &[
                "ls-tree",
                "-r",
                "-z",
                expected_commit,
                "--",
                "platform/minecraft/src",
            ],
        )?)?;
        let members = validate_manifest_tree_membership(&target.paths, &tree)
            .wrap_err_with(|| format!("{manifest_path}: actual pinned tag tree differs"))?;
        ensure!(
            members == expected_count,
            "{manifest_path}: expected {expected_count} release members, found {members}"
        );
        audit_actual_tag_blobs(&repository_root, target, &tree)
            .wrap_err_with(|| format!("{release_tag}: direct tag-byte audit failed"))?;
        total_members += members;
    }
    ensure!(
        total_members == 9_980,
        "expected exactly 9,980 directly audited release members"
    );
    Ok(())
}

// Reuse the production frozen probe's exact-root and object isolation, but
// additionally deny every transport in this test-only read route. No global
// environment/config is mutated and missing objects cannot trigger a fetch.
fn parity_git_command(root: &Path) -> Command {
    let mut command = frozen_git_command(root);
    command
        .env("GIT_ALLOW_PROTOCOL", "")
        .env("GIT_TERMINAL_PROMPT", "0");
    command
}

fn parity_git_stdout(root: &Path, args: &[&str]) -> Result<Vec<u8>> {
    let output = parity_git_command(root).args(args).output()?;
    ensure!(
        output.status.success(),
        "read-only Git {} failed: {}",
        args.join(" "),
        String::from_utf8_lossy(&output.stderr).trim()
    );
    ensure!(
        output.stderr.is_empty(),
        "read-only Git {} emitted diagnostics: {}",
        args.join(" "),
        String::from_utf8_lossy(&output.stderr).trim()
    );
    Ok(output.stdout)
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct SourceTreeEntry {
    mode: String,
    oid: String,
}

fn is_lower_hex(value: &str, length: usize) -> bool {
    value.len() == length
        && value
            .bytes()
            .all(|byte| byte.is_ascii_digit() || matches!(byte, b'a'..=b'f'))
}

fn parse_source_tree(bytes: &[u8]) -> Result<BTreeMap<String, SourceTreeEntry>> {
    let mut tree = BTreeMap::new();
    if bytes.is_empty() {
        return Ok(tree);
    }
    let records = bytes
        .strip_suffix(b"\0")
        .ok_or_else(|| eyre::eyre!("Git source tree is not NUL-terminated"))?;
    for record in records.split(|byte| *byte == 0) {
        let tab = record
            .iter()
            .position(|byte| *byte == b'\t')
            .ok_or_else(|| eyre::eyre!("Git source tree entry has no path separator"))?;
        let header = std::str::from_utf8(&record[..tab])?;
        let mut fields = header.split(' ');
        let (Some(mode), Some(kind), Some(oid), None) =
            (fields.next(), fields.next(), fields.next(), fields.next())
        else {
            bail!("malformed Git source tree identity");
        };
        ensure!(
            kind == "blob" && matches!(mode, "100644" | "100755"),
            "Git source tree contains a non-regular blob"
        );
        ensure!(is_lower_hex(oid, 40), "invalid Git source blob ID");
        let repository_path = std::str::from_utf8(&record[tab + 1..])?;
        let source_path = repository_path
            .strip_prefix("platform/minecraft/")
            .ok_or_else(|| eyre::eyre!("Git source path is outside the Minecraft project"))?;
        ensure!(
            is_safe_source_path(source_path),
            "unsafe Git source path '{source_path}'"
        );
        ensure!(
            tree.insert(
                source_path.to_owned(),
                SourceTreeEntry {
                    mode: mode.to_owned(),
                    oid: oid.to_owned()
                },
            )
            .is_none(),
            "duplicate Git source path '{source_path}'"
        );
    }
    Ok(tree)
}

fn validate_manifest_tree_membership(
    paths: &BTreeMap<String, BaselinePathRecord>,
    tree: &BTreeMap<String, SourceTreeEntry>,
) -> Result<usize> {
    let mut members = BTreeMap::new();
    for (path, record) in paths {
        let identity = (
            record.release_git_mode.as_deref(),
            record.release_blob_oid.as_deref(),
            record.release_sha256.as_deref(),
        );
        let (mode, oid, hash) = match identity {
            (None, None, None) => continue,
            (Some(mode), Some(oid), Some(hash)) => (mode, oid, hash),
            _ => bail!("incomplete release identity for '{path}'"),
        };
        ensure!(
            is_safe_source_path(path),
            "unsafe manifest release path '{path}'"
        );
        ensure!(
            matches!(mode, "100644" | "100755"),
            "invalid release mode for '{path}'"
        );
        ensure!(
            is_lower_hex(oid, 40),
            "invalid release blob ID for '{path}'"
        );
        ensure!(
            hash.strip_prefix("sha256:")
                .is_some_and(|value| is_lower_hex(value, 64)),
            "invalid release SHA-256 for '{path}'"
        );
        let expected = SourceTreeEntry {
            mode: mode.to_owned(),
            oid: oid.to_owned(),
        };
        ensure!(
            tree.get(path) == Some(&expected),
            "missing or changed tag-tree member '{path}'"
        );
        members.insert(path.clone(), expected);
    }
    for path in tree.keys() {
        ensure!(
            members.contains_key(path),
            "additional tag-tree member '{path}' absent from manifest"
        );
    }
    Ok(members.len())
}

fn audit_actual_tag_blobs(
    root: &Path,
    target: &ReleaseBaselineTargetReport,
    tree: &BTreeMap<String, SourceTreeEntry>,
) -> Result<()> {
    let mut child = parity_git_command(root)
        .args(["cat-file", "--batch"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .wrap_err("cannot start read-only tag blob reader")?;
    let mut stdin = child.stdin.take().expect("piped Git stdin");
    let mut stdout = BufReader::new(child.stdout.take().expect("piped Git stdout"));
    let mut stderr = child.stderr.take().expect("piped Git stderr");
    let diagnostics = std::thread::spawn(move || {
        let mut bytes = Vec::new();
        stderr.read_to_end(&mut bytes).map(|_| bytes)
    });
    let audit: Result<()> = (|| {
        // Do not cache by OID: every target/member is freshly read from Git.
        for (source_path, entry) in tree {
            let actual = read_batch_blob(&mut stdin, &mut stdout, &entry.oid)?;
            let expected_hash = target.paths[source_path]
                .release_sha256
                .as_deref()
                .expect("complete release identity checked before reading");
            ensure!(
                sha256(&actual) == expected_hash,
                "actual tag blob SHA-256 mismatch for '{source_path}'"
            );
            let generated_path = format!(
                "platform/minecraft/mc-version/{}/{source_path}",
                target.target_id
            );
            let generated = fs::read(root.join(&generated_path))
                .wrap_err_with(|| format!("cannot read '{generated_path}'"))?;
            let body = if Path::new(source_path)
                .extension()
                .is_some_and(|extension| extension.eq_ignore_ascii_case("java"))
            {
                remove_generated_java_banner(&generated)
                    .map_err(|reason| eyre::eyre!("{generated_path}: {reason}"))?
            } else {
                generated
            };
            ensure!(
                body == actual,
                "generated bytes differ from actual tag blob for '{generated_path}'"
            );
        }
        Ok(())
    })();
    drop(stdin);
    drop(stdout);
    if audit.is_err() {
        let _ = child.kill();
    }
    let status = child.wait()?;
    let stderr = diagnostics
        .join()
        .map_err(|_| eyre::eyre!("Git diagnostics reader panicked"))??;
    ensure!(
        stderr.is_empty(),
        "tag blob reader emitted diagnostics: {}",
        String::from_utf8_lossy(&stderr).trim()
    );
    audit?;
    ensure!(status.success(), "tag blob reader failed");
    Ok(())
}

fn read_batch_blob(
    stdin: &mut impl Write,
    stdout: &mut impl BufRead,
    expected_oid: &str,
) -> Result<Vec<u8>> {
    ensure!(
        is_lower_hex(expected_oid, 40),
        "invalid requested tag blob ID"
    );
    writeln!(stdin, "{expected_oid}")?;
    stdin.flush()?;
    let mut header = Vec::new();
    (&mut *stdout).take(256).read_until(b'\n', &mut header)?;
    let header = header
        .strip_suffix(b"\n")
        .ok_or_else(|| eyre::eyre!("tag blob reader ended before a bounded header"))?;
    let mut fields = std::str::from_utf8(header)?.split(' ');
    let (Some(oid), Some("blob"), Some(size), None) =
        (fields.next(), fields.next(), fields.next(), fields.next())
    else {
        bail!("tag object is missing or is not a blob");
    };
    ensure!(oid == expected_oid, "tag blob ID changed while reading");
    ensure!(
        !size.is_empty() && size.bytes().all(|byte| byte.is_ascii_digit()),
        "invalid tag blob size"
    );
    let size = size.parse::<usize>()?;
    ensure!(
        size <= MAX_SOURCE_BLOB_BYTES,
        "tag source blob is too large"
    );
    let mut bytes = Vec::new();
    bytes.try_reserve_exact(size)?;
    bytes.resize(size, 0);
    stdout.read_exact(&mut bytes)?;
    let mut terminator = [0];
    stdout.read_exact(&mut terminator)?;
    ensure!(terminator == [b'\n'], "tag blob stream lost framing");
    Ok(bytes)
}

fn is_safe_source_path(path: &str) -> bool {
    path.starts_with("src/")
        && !path.contains('\\')
        && !path.contains(':')
        && !path.chars().any(char::is_control)
        && path
            .split('/')
            .all(|component| !component.is_empty() && component != "." && component != "..")
}

fn remove_generated_java_banner(generated: &[u8]) -> Result<Vec<u8>, &'static str> {
    let (bom, after_bom) = if let Some(rest) = generated.strip_prefix(UTF8_BOM) {
        (UTF8_BOM, rest)
    } else {
        (&[][..], generated)
    };
    let after_banner = after_bom
        .strip_prefix(GENERATED_BANNER)
        .ok_or("missing exact generated Java banner")?;
    let (banner_line_ending, source) = if let Some(rest) = after_banner.strip_prefix(b"\r\n") {
        (&b"\r\n"[..], rest)
    } else if let Some(rest) = after_banner.strip_prefix(b"\n") {
        (&b"\n"[..], rest)
    } else if let Some(rest) = after_banner.strip_prefix(b"\r") {
        (&b"\r"[..], rest)
    } else {
        return Err("generated Java banner has no line ending");
    };
    if source.starts_with(UTF8_BOM) {
        return Err("Java BOM occurs after generated banner");
    }
    if banner_line_ending != preferred_line_ending(source) {
        return Err("generated Java banner uses a different line ending from the source");
    }

    let mut original = Vec::with_capacity(bom.len() + source.len());
    original.extend_from_slice(bom);
    original.extend_from_slice(source);
    Ok(original)
}

fn preferred_line_ending(source: &[u8]) -> &'static [u8] {
    if let Some(index) = source.iter().position(|byte| *byte == b'\n') {
        if index > 0 && source[index - 1] == b'\r' {
            b"\r\n"
        } else {
            b"\n"
        }
    } else if source.contains(&b'\r') {
        b"\r"
    } else {
        b"\n"
    }
}

#[test]
fn source_tree_parser_accepts_exact_regular_members() {
    let bytes = format!(
        "100644 blob {}\tplatform/minecraft/src/main/java/A.java\0\
         100755 blob {}\tplatform/minecraft/src/test/script.sh\0",
        "a".repeat(40),
        "b".repeat(40),
    );
    let tree = parse_source_tree(bytes.as_bytes()).unwrap();
    assert_eq!(tree.len(), 2);
    assert_eq!(tree["src/main/java/A.java"].oid, "a".repeat(40));
    assert_eq!(tree["src/test/script.sh"].mode, "100755");
}

#[test]
fn source_tree_parser_rejects_unsafe_nonregular_duplicate_and_malformed_entries() {
    let oid = "a".repeat(40);
    let valid = format!("100644 blob {oid}\tplatform/minecraft/src/A.java\0");
    for invalid in [
        valid.trim_end_matches('\0').to_owned(),
        format!("{valid}{valid}"),
        format!("{valid}\0"),
        format!("120000 blob {oid}\tplatform/minecraft/src/A.java\0"),
        format!("160000 commit {oid}\tplatform/minecraft/src/A.java\0"),
        format!("100644 blob {oid}\tplatform/minecraft/src/../A.java\0"),
        format!("100644 blob {oid}\tplatform/minecraft/src/C:/A.java\0"),
        format!("100644 blob {oid}\tplatform/minecraft/src/a\\A.java\0"),
        format!("100644 blob {oid}\tplatform/minecraft/src/a\nA.java\0"),
        format!("100644 blob {oid}\telsewhere/src/A.java\0"),
        format!("100644  blob {oid}\tplatform/minecraft/src/A.java\0"),
        format!(
            "100644 blob {}\tplatform/minecraft/src/A.java\0",
            "A".repeat(40)
        ),
        format!("100644 blob {oid} platform/minecraft/src/A.java\0"),
    ] {
        assert!(
            parse_source_tree(invalid.as_bytes()).is_err(),
            "accepted {invalid:?}"
        );
    }
}

#[test]
fn manifest_tree_membership_rejects_omissions_additions_and_changed_identities() {
    use super::release_baseline::BaselinePathClass;

    let path = "src/A.java".to_owned();
    let entry = SourceTreeEntry {
        mode: "100644".to_owned(),
        oid: "a".repeat(40),
    };
    let tree = BTreeMap::from([(path.clone(), entry.clone())]);
    let mut paths = BTreeMap::from([(
        path.clone(),
        BaselinePathRecord {
            classification: BaselinePathClass::Unchanged,
            release_git_mode: Some(entry.mode.clone()),
            release_blob_oid: Some(entry.oid.clone()),
            release_sha256: Some(sha256(b"original\n")),
            canonical_sha256: None,
            release_overlay_path: None,
        },
    )]);
    assert_eq!(validate_manifest_tree_membership(&paths, &tree).unwrap(), 1);
    assert!(validate_manifest_tree_membership(&paths, &BTreeMap::new()).is_err());
    assert!(validate_manifest_tree_membership(&BTreeMap::new(), &tree).is_err());
    let mut additional = tree.clone();
    additional.insert("src/extra.java".to_owned(), entry);
    assert!(validate_manifest_tree_membership(&paths, &additional).is_err());
    for (mode, oid, hash) in [
        (
            Some("100755".to_owned()),
            Some("a".repeat(40)),
            Some(sha256(b"original\n")),
        ),
        (
            Some("100644".to_owned()),
            Some("b".repeat(40)),
            Some(sha256(b"original\n")),
        ),
        (Some("100644".to_owned()), None, Some(sha256(b"original\n"))),
        (Some("100644".to_owned()), Some("a".repeat(40)), None),
        (
            Some("100644".to_owned()),
            Some("a".repeat(40)),
            Some("sha256:invalid".to_owned()),
        ),
        (
            Some("120000".to_owned()),
            Some("a".repeat(40)),
            Some(sha256(b"original\n")),
        ),
    ] {
        let record = paths.get_mut(&path).unwrap();
        record.release_git_mode = mode;
        record.release_blob_oid = oid;
        record.release_sha256 = hash;
        assert!(validate_manifest_tree_membership(&paths, &tree).is_err());
    }
}

#[test]
fn batch_reader_preserves_binary_blob_bytes_and_exact_framing() {
    let oid = "a".repeat(40);
    let body = b"\xEF\xBB\xBFline one\r\nline two\n\0\xFF";
    let mut response = format!("{oid} blob {}\n", body.len()).into_bytes();
    response.extend_from_slice(body);
    response.push(b'\n');
    let mut stdout = std::io::Cursor::new(response);
    let mut requests = Vec::new();
    assert_eq!(
        read_batch_blob(&mut requests, &mut stdout, &oid).unwrap(),
        body
    );
    assert_eq!(requests, format!("{oid}\n").as_bytes());
    assert_eq!(stdout.position(), stdout.get_ref().len() as u64);
}

#[test]
fn batch_reader_rejects_missing_wrong_identity_size_and_truncated_framing() {
    let oid = "a".repeat(40);
    for response in [
        format!("{oid} missing\n"),
        format!("{} blob 1\nx\n", "b".repeat(40)),
        format!("{oid} tree 1\nx\n"),
        format!("{oid} blob -1\n"),
        format!("{oid} blob +1\n"),
        format!("{oid} blob {}\n", MAX_SOURCE_BLOB_BYTES + 1),
        format!("{oid} blob 999999999999999999999999999999999999999\n"),
        format!("{oid} blob 2\nx"),
        format!("{oid} blob 1\nx!"),
        format!("{oid} blob 1\nx"),
        format!("{oid} blob 1 extra\nx\n"),
        format!("{oid} blob {}", "1".repeat(300)),
    ] {
        let mut stdout = std::io::Cursor::new(response.as_bytes());
        assert!(
            read_batch_blob(&mut Vec::new(), &mut stdout, &oid).is_err(),
            "accepted {response:?}"
        );
    }
    assert!(read_batch_blob(&mut Vec::new(), &mut std::io::Cursor::new(b""), "invalid").is_err());
}

#[test]
fn java_banner_removal_preserves_bom_and_each_source_line_ending() {
    for bom in [&[][..], UTF8_BOM] {
        for ending in [&b"\n"[..], &b"\r\n"[..], &b"\r"[..]] {
            let mut generated = bom.to_vec();
            generated.extend_from_slice(GENERATED_BANNER);
            generated.extend_from_slice(ending);
            generated.extend_from_slice(b"package example;");
            generated.extend_from_slice(ending);
            generated.extend_from_slice(b"// unchanged");
            let mut original = bom.to_vec();
            original.extend_from_slice(b"package example;");
            original.extend_from_slice(ending);
            original.extend_from_slice(b"// unchanged");
            assert_eq!(remove_generated_java_banner(&generated).unwrap(), original);
        }
    }
}

#[test]
fn java_banner_removal_rejects_altered_banner_bom_and_line_ending() {
    for generated in [
        b"package example;\n".to_vec(),
        [GENERATED_BANNER, b" changed\npackage example;\n"].concat(),
        GENERATED_BANNER.to_vec(),
        [GENERATED_BANNER, b"\n", UTF8_BOM, b"package example;\n"].concat(),
        [GENERATED_BANNER, b"\r\npackage example;\n"].concat(),
    ] {
        assert!(remove_generated_java_banner(&generated).is_err());
    }
}

#[test]
fn direct_tag_probe_uses_child_local_object_isolation_and_no_transport() {
    let command = parity_git_command(Path::new("."));
    let environment = command.get_envs().collect::<BTreeMap<_, _>>();
    for (key, expected) in [
        ("GIT_NO_LAZY_FETCH", "1"),
        ("GIT_NO_REPLACE_OBJECTS", "1"),
        ("GIT_OPTIONAL_LOCKS", "0"),
        ("GIT_ALLOW_PROTOCOL", ""),
        ("GIT_TERMINAL_PROMPT", "0"),
    ] {
        assert_eq!(
            environment[std::ffi::OsStr::new(key)],
            Some(std::ffi::OsStr::new(expected))
        );
    }
}
