// GENERATED by sfm-propagate-changes; edit the primary source or reconcile this file.
package ca.teamdman.sfm.client.jei;

public class FallingAnvilExperienceShardRecipe extends FallingAnvilRecipe {

}
