// GENERATED by sfm-propagate-changes; edit the primary source or reconcile this file.
package ca.teamdman.sfml.intellisense;

import ca.teamdman.sfm.client.screen.widget.PickListItem;
import ca.teamdman.sfml.manipulation.ManipulationResult;

public interface IntellisenseAction extends PickListItem {
    ManipulationResult perform(IntellisenseContext context);
}
