// GENERATED by sfm-propagate-changes; edit the primary source or reconcile this file.
package ca.teamdman.sfm.client.text_editor.action;

public record KeyboardImpulse(
        int keyCode,
        int scanCode,
        int modifiers
) {
}
