// GENERATED by sfm-propagate-changes; edit the primary source or reconcile this file.
package ca.teamdman.sfm.client.screen;

import java.util.function.Consumer;

public record TomlEditScreenOpenContext(
        String textContents,
        Consumer<String> saveCallback
) {
}
