//file:noinspection DependencyNotationArgument
// TODO remove when fixed in RFG ^
/*
 * Add your dependencies here. Supported configurations:
 *  - api("group:name:version:classifier"): if you use the types from this dependency in the public API of this mod
 *       Available at runtime and compiletime for mods depending on this mod
 *  - implementation("g:n:v:c"): if you need this for internal implementation details of the mod, but none of it is visible via the public API
 *       Available at runtime but not compiletime for mods depending on this mod
 *  - compileOnly("g:n:v:c"): if the mod you're building doesn't need this dependency during runtime at all, e.g. for optional mods
 *       Not available at all for mods depending on this mod, only visible at compiletime for this mod
 *  - compileOnlyApi("g:n:v:c"): like compileOnly, but also visible at compiletime for mods depending on this mod
 *       Available at compiletime but not runtime for mods depending on this mod
 *  - runtimeOnlyNonPublishable("g:n:v:c"): if you want to include a mod in this mod's runClient/runServer runs, but not publish it as a dependency
 *       Not available at all for mods depending on this mod, only visible at runtime for this mod
 *  - devOnlyNonPublishable("g:n:v:c"): a combination of runtimeOnlyNonPublishable and compileOnly for dependencies present at both compiletime and runtime,
 *       but not published as Maven dependencies - useful for RFG-deobfuscated dependencies or local testing
 *  - runtimeOnly("g:n:v:c"): if you don't need this at compile time, but want it to be present at runtime
 *       Available at runtime for mods depending on this mod
 *  - annotationProcessor("g:n:v:c"): mostly for java compiler plugins, if you know you need this, use it, otherwise don't worry
 *  - testCONFIG("g:n:v:c") - replace CONFIG by one of the above (except api), same as above but for the test sources instead of main
 *
 *  - shadowImplementation("g:n:v:c"): effectively the same as API, but the dependency is included in your jar under a renamed package name
 *       Requires you to enable usesShadowedDependencies in gradle.properties
 *       For more info, see https://github.com/GregTechCEu/Buildscripts/blob/master/docs/shadow.md
 *
 * You can exclude transitive dependencies (dependencies of the chosen dependency) by appending { transitive = false } if needed,
 * but use this sparingly as it can break using your mod as another mod's dependency if you're not careful.
 *
 * To depend on obfuscated jars you can use `devOnlyNonPublishable(rfg.deobf("dep:spec:1.2.3"))` to fetch an obfuscated jar from maven,
 * or `devOnlyNonPublishable(rfg.deobf(project.files("libs/my-mod-jar.jar")))` to use a file.
 *
 * To add a mod with CurseMaven, replace '("g:n:v:c")' in the above with 'rfg.deobf("curse.maven:project_slug-project_id:file_id")'
 * Example: devOnlyNonPublishable(rfg.deobf("curse.maven:top-245211:2667280"))
 *
 * Gradle names for some of the configuration can be misleading, compileOnlyApi and runtimeOnly both get published as dependencies in Maven, but compileOnly does not.
 * The buildscript adds runtimeOnlyNonPublishable to also have a runtime dependency that's not published.
 *
 * For more details, see https://docs.gradle.org/8.4/userguide/java_library_plugin.html#sec:java_library_configurations_graph
 */


repositories {
    // Other repositories described by default:
    // CleanroomMC: https://maven.cleanroommc.com
    exclusiveContent {
        forRepository {
            //noinspection ForeignDelegate
            maven {
                name = 'Curse Maven'
                url = 'https://www.cursemaven.com'
                // url = 'https://beta.cursemaven.com'
            }
        }
        filter {
            includeGroup 'curse.maven'
        }
    }
    exclusiveContent {
        forRepository {
            //noinspection ForeignDelegate
            maven {
                name = 'Modrinth'
                url = 'https://api.modrinth.com/maven'
            }
        }
        filter {
            includeGroup 'maven.modrinth'
        }
    }
    maven {
        name = 'BlameJared Maven'
        url = 'https://maven.blamejared.com'
    }
    maven {
        name = 'GTNH Maven'
        url = 'https://nexus.gtnewhorizons.com/repository/public/'
    }
    maven {
        name = 'GTCEu Maven'
        url = 'https://maven.gtceu.com'
    }
}

dependencies {
    compileOnlyApi 'org.jetbrains:annotations:24.1.0'
    annotationProcessor 'org.jetbrains:annotations:24.1.0'

    antlr("org.antlr:antlr4:4.9.1")
    embed("org.antlr:antlr4-runtime:4.9.1") { transitive = false }
    embed("com.github.mpkorstanje:simmetrics-core:4.1.1") { transitive = false }

    // For testing with AE2
    runtimeOnlyNonPublishable(rfg.deobf("curse.maven:ae2-extended-life-570458:6302098"))
    runtimeOnlyNonPublishable(rfg.deobf("curse.maven:ae2-fluid-crafting-rework-623955:5504001"))
    runtimeOnlyNonPublishable(rfg.deobf("curse.maven:nae2-884359:5380800"))


    compileOnly('mezz.jei:jei_1.12.2:4.16.1.302')
    compileOnly(rfg.deobf('curse.maven:packagedauto-308380:7222356'))
    runtimeOnlyNonPublishable(rfg.deobf('curse.maven:packagedauto-308380:7222356'))
    runtimeOnlyNonPublishable rfg.deobf('curse.maven:top-245211:2667280') // TOP 1.4.28


    // For testing with Thermal Expansion (and its dependencies)
    runtimeOnlyNonPublishable(rfg.deobf("curse.maven:thermal-expansion-69163:2926431"))
    runtimeOnlyNonPublishable(rfg.deobf("curse.maven:thermal-foundation-222880:2926428"))
    runtimeOnlyNonPublishable(rfg.deobf("curse.maven:cofh-core-69162:2920433"))
    runtimeOnlyNonPublishable(rfg.deobf("curse.maven:codechicken-lib-1-8-242818:2779848"))
    runtimeOnlyNonPublishable(rfg.deobf("curse.maven:redstone-flux-270789:2920436"))
    runtimeOnlyNonPublishable(rfg.deobf("curse.maven:cofh-world-271384:2920434"))

    // EnderIO doesn't work in deobf for some reason, uncomment and run obfuscated client
    //    implementation(("maven.modrinth:enderio:ozde4Meh"))
    //    implementation(("maven.modrinth:endercore:ObLYMdMS"))

    compileOnly(rfg.deobf("curse.maven:storage-drawers-223852:5981297")) { transitive = false }
    runtimeOnlyNonPublishable(rfg.deobf("curse.maven:storage-drawers-223852:5981297")) { transitive = false }
    runtimeOnlyNonPublishable(rfg.deobf("curse.maven:chameleon-230497:2450900")) { transitive = false }

    testImplementation 'org.openjdk.jmh:jmh-core:1.37'
    testImplementation 'org.openjdk.jmh:jmh-generator-annprocess:1.37'
    testImplementation 'org.openjdk.jmh:jmh-generator-bytecode:1.37'
    testAnnotationProcessor 'org.openjdk.jmh:jmh-generator-annprocess:1.37'

}