package ca.teamdman.sfm.client.screen.review.comment;
import org.junit.jupiter.api.Test;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;
class SFMReviewCommentUiTests {
 @Test void hashtagsAreDerivedFromTextIncludingQuotedForms(){assertEquals(java.util.Set.of("#problem","#needs review"),SFMCommentHashtags.derive("#Problem investigate #\"needs review\""));}
 @Test void literalCreateEditAndArchiveUseTheSameProductionPanelPathAsUserInput(){var panel=new SFMReviewCommentPanel(new SFMFixtureReviewCommentDataSource());panel.selectLiteral(new SFMReviewCommentDataSource.RangeView(SFMFixtureReviewCommentDataSource.AFTER,20,30));panel.beginCreate();panel.replaceDraftText("#question initial");panel.submitText();var created=panel.session().comments().stream().filter(c->c.text().equals("#question initial")).findFirst().orElseThrow();assertEquals(java.util.Set.of("#question"),SFMCommentHashtags.derive(created.text()));panel.beginEdit();panel.replaceDraftText("#approved checked");panel.submitText();assertEquals(java.util.Set.of("#approved"),SFMCommentHashtags.derive(panel.session().comments().stream().filter(c->c.id().equals(created.id())).findFirst().orElseThrow().text()));panel.archiveActive();assertTrue(panel.session().comments().stream().filter(c->c.id().equals(created.id())).findFirst().orElseThrow().archived());}
 @Test void fixtureKeepsBeforeAfterOverlapMigrationAndLegacyProjection(){var v=new SFMFixtureReviewCommentDataSource().refresh();assertEquals(List.of(SFMReviewCommentDataSource.Side.BEFORE,SFMReviewCommentDataSource.Side.AFTER),v.documents().stream().map(SFMReviewCommentDataSource.DocumentView::side).toList());assertTrue(v.comments().stream().filter(c->c.ranges().stream().anyMatch(r->r.startByte()<68&&r.endByte()>60)).count()>=2);assertEquals(List.of(SFMReviewCommentDataSource.EvaluationStatus.RESOLVED_EXACTLY,SFMReviewCommentDataSource.EvaluationStatus.CONTENT_CHANGED,SFMReviewCommentDataSource.EvaluationStatus.INVALID_RULE),v.migrations().stream().map(SFMReviewCommentDataSource.MigrationView::status).toList());assertFalse(v.legacyRows().isEmpty());}
 @Test void styleEditingIsTypedAndDoesNotMutateCommentSemantics(){var s=new SFMFixtureReviewCommentDataSource();var comments=s.refresh().comments();s.updateStyleColour("problem-underline",SFMReviewCommentDataSource.StyleChannel.UNDERLINE,0xFFAA11CC);assertEquals(0xFFAA11CC,s.refresh().styleRules().stream().filter(r->r.id().equals("problem-underline")).findFirst().orElseThrow().underline());assertEquals(comments,s.refresh().comments());}
}
