// GENERATED by sfm-propagate-changes; edit the primary source or reconcile this file.
package ca.teamdman.sfm.client.text_editor.action;

import net.minecraft.client.input.KeyEvent;

public record KeyboardImpulse(
        KeyEvent event
) {
}
