// GENERATED by sfm-propagate-changes; edit the primary source or reconcile this file.
package ca.teamdman.sfm.common.program;

import java.time.Duration;

public interface IProgramHooks {
    default void onProgramDidSomething(Duration elapsed) {}
}
