// GENERATED by sfm-propagate-changes; edit the primary source or reconcile this file.
package ca.teamdman.sfml.manipulation;

public record ManipulationResult(
        String content,
        int cursorPosition,
        int selectionCursorPosition
) {
}
