[package]
name = "emc_finder"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
itertools = "0.13.0"
rayon = "1.10.0"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
uuid = { version = "1.10.0", features = ["fast-rng", "v4"] }
