// GENERATED by sfm-propagate-changes; edit the primary source or reconcile this file.
package ca.teamdman.sfm.client.screen.widget;

import net.minecraft.network.chat.Component;

public interface PickListItem {
    Component getComponent();
}
